/*
 * Copyright (c) 2024, Analog Devices Incorporated, All Rights Reserved
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef __ADI_C2CC_INTERNAL_H__
#define __ADI_C2CC_INTERNAL_H__

/* register offsets */
#define ADI_C2CC_REG_CHECKPOLY_START    0x160
#define ADI_C2CC_REG_TRAINPOLY_START    0x180
#define ADI_C2CC_REG_TRAINSTAT1_START   0x088
#define ADI_C2CC_REG_TRAINSTAT2_START   0x0A8
#define ADI_C2CC_REG_TRAINSTAT3 0x0C8
#define ADI_C2CC_REG_CALIBCTRL1 0x054
#define ADI_C2CC_REG_CLKCTRL1   0x004
#define ADI_C2CC_REG_CLKCTRL2   0x040
#define ADI_C2CC_REG_CONFIG     0x000
#define ADI_C2CC_REG_DLYTRIM1   0x044
#define ADI_C2CC_REG_DLYTRIM4   0x050
#define ADI_C2CC_REG_INT_STATUS 0x080
#define ADI_C2CC_REG_INTPORTEN0 0x200
#define ADI_C2CC_REG_INTPORTEN9 0x224
#define ADI_C2CC_REG_OTSTS      0x070
#define ADI_C2CC_REG_TRAINPARAM1        0x1A0
#define ADI_C2CC_REG_TRAINPARAM2        0x1A4
#define ADI_C2CC_REG_TRAINPARAM3        0x1A8
#define ADI_C2CC_REG_TRAINPARAM4        0x1AC
#define ADI_C2CC_REG_TRAINPARAM5        0x1B0
#define ADI_C2CC_REG_TRAINPARAM6        0x1B4
#define ADI_C2CC_REG_DLYTRIM2   0x048

#define ADI_C2CC_REG_CHECKPOLY(lane, edge)      (ADI_C2CC_REG_CHECKPOLY_START + ((lane) * 8) + ((edge) * 4))
#define ADI_C2CC_REG_TRAINPOLY(lane, edge)      (ADI_C2CC_REG_TRAINPOLY_START + ((lane) * 8) + ((edge) * 4))
#define ADI_C2CC_REG_TRAINSTAT1(lane, edge)     (ADI_C2CC_REG_TRAINSTAT1_START + ((lane) * 8) + ((edge) * 4))
#define ADI_C2CC_REG_TRAINSTAT2(lane, edge)     (ADI_C2CC_REG_TRAINSTAT2_START + ((lane) * 8) + ((edge) * 4))

/* bitfields */
#define ADI_C2CC_BITP_CAL_BAD_CNT       0
#define ADI_C2CC_BITP_CAL_EARLY_CNT     16
#define ADI_C2CC_BITP_CAL_FAIL_CNT      0
#define ADI_C2CC_BITP_CAL_LATE_CNT      16
#define ADI_C2CC_BITP_LFSR_POLY 0
#define ADI_C2CC_BITP_LFSR_POLY_CHECK   0
#define ADI_C2CC_BITP_LFSR_SEED 16
#define ADI_C2CC_BITP_AXI_INIT_AROT     8
#define ADI_C2CC_BITP_AXI_INIT_AWOT     0
#define ADI_C2CC_BITP_AXI_INIT_EN       1
#define ADI_C2CC_BITP_AXI_INIT_WOT      4
#define ADI_C2CC_BITP_BLKTRF    0
#define ADI_C2CC_BITP_C2C_EN    0
#define ADI_C2CC_BITP_CMD2TXCLKSW       16
#define ADI_C2CC_BITP_DEV_TX_CLK_DIV    6
#define ADI_C2CC_BITP_INT_EN    3
#define ADI_C2CC_BITP_LDDUR     0
#define ADI_C2CC_BITP_MTCHDUR   16
#define ADI_C2CC_BITP_PLL_TX_CLK_DIV    12
#define ADI_C2CC_BITP_POWERUP_CAL_START 0
#define ADI_C2CC_BITP_PWR_UP_RX_CAL_IRQ 16
#define ADI_C2CC_BITP_PWR_UP_TX_CAL_IRQ 15
#define ADI_C2CC_BITP_RESP2CMD  0
#define ADI_C2CC_BITP_ROSC_TX_CLK_DIV   0
#define ADI_C2CC_BITP_RXCLK_DELAY       0
#define ADI_C2CC_BITP_RXCLK_DELAY_TRAIN 0
#define ADI_C2CC_BITP_RXCMD2LD  16
#define ADI_C2CC_BITP_RXCMD2TRNTRM      0
#define ADI_C2CC_BITP_SWBCKCLK  16
#define ADI_C2CC_BITP_SWBCKTRM  0
#define ADI_C2CC_BITP_TRAIN_DEV_TX_CLK_DIV      6
#define ADI_C2CC_BITP_TRAIN_PLL_TX_CLK_DIV      12
#define ADI_C2CC_BITP_TRAIN_ROSC_TX_CLK_DIV     0
#define ADI_C2CC_BITP_TXCALDONE 16
#define ADI_C2CC_BITP_TXCLKSW2PTRN      16
#define ADI_C2CC_BITP_TXPTRNDUR 0

#define ADI_C2CC_BITP_AXI_OUTSTANDING   ADI_C2CC_BITP_AXI_INIT_AWOT
#define ADI_C2CC_BITP_TXDATA_DELAY(lane) (4 * lane)
#define ADI_C2CC_BITP_RXDATA_DELAY(lane) (16 + ADI_C2CC_BITP_TXDATA_DELAY(lane))

#define ADI_C2CC_BITM_CAL_BAD_CNT       0x0000FFFF
#define ADI_C2CC_BITM_CAL_EARLY_CNT     0xFFFF0000
#define ADI_C2CC_BITM_CAL_FAIL_CNT      0x0000FFFF
#define ADI_C2CC_BITM_CAL_LATE_CNT      0xFFFF0000
#define ADI_C2CC_BITM_LFSR_POLY 0x0000FFFF
#define ADI_C2CC_BITM_LFSR_POLY_CHECK   0x0000FFFF
#define ADI_C2CC_BITM_LFSR_SEED 0xFFFF0000
#define ADI_C2CC_BITM_AXI_INIT_AROT     0x00000F00
#define ADI_C2CC_BITM_AXI_INIT_AWOT     0x0000000F
#define ADI_C2CC_BITM_AXI_INIT_EN       0x00000002
#define ADI_C2CC_BITM_AXI_INIT_WOT      0x000000F0
#define ADI_C2CC_BITM_BLKTRF    0x0000FFFF
#define ADI_C2CC_BITM_C2C_EN    0x00000001
#define ADI_C2CC_BITM_CMD2TXCLKSW       0xFFFF0000
#define ADI_C2CC_BITM_DEV_TX_CLK_DIV    0x00000FC0
#define ADI_C2CC_BITM_INT_EN    0x00000008
#define ADI_C2CC_BITM_LDDUR     0x0000FFFF
#define ADI_C2CC_BITM_MTCHDUR   0xFFFF0000
#define ADI_C2CC_BITM_PLL_TX_CLK_DIV    0x0003F000
#define ADI_C2CC_BITM_POWERUP_CAL_START 0x00000001
#define ADI_C2CC_BITM_PWR_UP_RX_CAL_IRQ 0x00010000
#define ADI_C2CC_BITM_PWR_UP_TX_CAL_IRQ 0x00008000
#define ADI_C2CC_BITM_RESP2CMD  0x0000FFFF
#define ADI_C2CC_BITM_ROSC_TX_CLK_DIV   0x0000003F
#define ADI_C2CC_BITM_RXCLK_DELAY       0x0000003F
#define ADI_C2CC_BITM_RXCLK_DELAY_TRAIN 0x0000003F
#define ADI_C2CC_BITM_RXCMD2LD  0xFFFF0000
#define ADI_C2CC_BITM_RXCMD2TRNTRM      0x0000FFFF
#define ADI_C2CC_BITM_SWBCKCLK  0xFFFF0000
#define ADI_C2CC_BITM_SWBCKTRM  0x0000FFFF
#define ADI_C2CC_BITM_TRAIN_DEV_TX_CLK_DIV      0x00000FC0
#define ADI_C2CC_BITM_TRAIN_PLL_TX_CLK_DIV      0x0003F000
#define ADI_C2CC_BITM_TRAIN_ROSC_TX_CLK_DIV     0x0000003F
#define ADI_C2CC_BITM_TXCALDONE 0xFFFF0000
#define ADI_C2CC_BITM_TXCLKSW2PTRN      0xFFFF0000
#define ADI_C2CC_BITM_TXPTRNDUR 0x0000FFFF

#define ADI_C2CC_BITM_AXI_OUTSTANDING   (ADI_C2CC_BITM_AXI_INIT_AROT | ADI_C2CC_BITM_AXI_INIT_WOT | ADI_C2CC_BITM_AXI_INIT_AWOT)
#define ADI_C2CC_BITM_TXDATA_DELAY(lane) (0xF << ADI_C2CC_BITP_TXDATA_DELAY(lane))
#define ADI_C2CC_BITM_RXDATA_DELAY(lane) (0xF << ADI_C2CC_BITP_RXDATA_DELAY(lane))

/* read macros */
#define ADI_C2CC_READ_AXI_INIT_AROT(base)       ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_OTSTS, ADI_C2CC_BITP_AXI_INIT_AROT, ADI_C2CC_BITM_AXI_INIT_AROT)
#define ADI_C2CC_READ_AXI_INIT_AWOT(base)       ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_OTSTS, ADI_C2CC_BITP_AXI_INIT_AWOT, ADI_C2CC_BITM_AXI_INIT_AWOT)
#define ADI_C2CC_READ_AXI_INIT_EN(base) ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CONFIG, ADI_C2CC_BITP_AXI_INIT_EN, ADI_C2CC_BITM_AXI_INIT_EN)
#define ADI_C2CC_READ_AXI_INIT_WOT(base)        ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_OTSTS, ADI_C2CC_BITP_AXI_INIT_WOT, ADI_C2CC_BITM_AXI_INIT_WOT)
#define ADI_C2CC_READ_BF32      adi_c2cc_read_bf32
#define ADI_C2CC_READ_BLKTRF(base)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM1, ADI_C2CC_BITP_BLKTRF, ADI_C2CC_BITM_BLKTRF)
#define ADI_C2CC_READ_C2C_EN(base)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CONFIG, ADI_C2CC_BITP_C2C_EN, ADI_C2CC_BITM_C2C_EN)
#define ADI_C2CC_READ_CHECKPOLY_LFSR_POLY(base, lane, edge)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CHECKPOLY(lane, edge), ADI_C2CC_BITP_LFSR_POLY_CHECK, ADI_C2CC_BITM_LFSR_POLY_CHECK)
#define ADI_C2CC_READ_CMD2TXCLKSW(base) ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM1, ADI_C2CC_BITP_CMD2TXCLKSW, ADI_C2CC_BITM_CMD2TXCLKSW)
#define ADI_C2CC_READ_DEV_TX_CLK_DIV(base)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CLKCTRL1, ADI_C2CC_BITP_DEV_TX_CLK_DIV, ADI_C2CC_BITM_DEV_TX_CLK_DIV)
#define ADI_C2CC_READ_INT_EN(base)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CONFIG, ADI_C2CC_BITP_INT_EN, ADI_C2CC_BITM_INT_EN)
#define ADI_C2CC_READ_LDDUR(base)       ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM2, ADI_C2CC_BITP_LDDUR, ADI_C2CC_BITM_LDDUR)
#define ADI_C2CC_READ_MTCHDUR(base)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM2, ADI_C2CC_BITP_MTCHDUR, ADI_C2CC_BITM_MTCHDUR)
#define ADI_C2CC_READ_PLL_TX_CLK_DIV(base)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CLKCTRL1, ADI_C2CC_BITP_PLL_TX_CLK_DIV, ADI_C2CC_BITM_PLL_TX_CLK_DIV)
#define ADI_C2CC_READ_POWERUP_CAL_START(base)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CALIBCTRL1, ADI_C2CC_BITP_POWERUP_CAL_START, ADI_C2CC_BITM_POWERUP_CAL_START)
#define ADI_C2CC_READ_PWR_UP_RX_CAL_IRQ(base)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_INT_STATUS, ADI_C2CC_BITP_PWR_UP_RX_CAL_IRQ, ADI_C2CC_BITM_PWR_UP_RX_CAL_IRQ)
#define ADI_C2CC_READ_PWR_UP_TX_CAL_IRQ(base)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_INT_STATUS, ADI_C2CC_BITP_PWR_UP_TX_CAL_IRQ, ADI_C2CC_BITM_PWR_UP_TX_CAL_IRQ)
#define ADI_C2CC_READ_RESP2CMD(base)    ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM3, ADI_C2CC_BITP_RESP2CMD, ADI_C2CC_BITM_RESP2CMD)
#define ADI_C2CC_READ_ROSC_TX_CLK_DIV(base)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CLKCTRL1, ADI_C2CC_BITP_ROSC_TX_CLK_DIV, ADI_C2CC_BITM_ROSC_TX_CLK_DIV)
#define ADI_C2CC_READ_RXCLK_DELAY(base) ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_DLYTRIM1, ADI_C2CC_BITP_RXCLK_DELAY, ADI_C2CC_BITM_RXCLK_DELAY)
#define ADI_C2CC_READ_RXCLK_DELAY_TRAIN(base)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_DLYTRIM4, ADI_C2CC_BITP_RXCLK_DELAY_TRAIN, ADI_C2CC_BITM_RXCLK_DELAY_TRAIN)
#define ADI_C2CC_READ_RXCMD2LD(base)    ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM3, ADI_C2CC_BITP_RXCMD2LD, ADI_C2CC_BITM_RXCMD2LD)
#define ADI_C2CC_READ_RXCMD2TRNTRM(base)        ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM4, ADI_C2CC_BITP_RXCMD2TRNTRM, ADI_C2CC_BITM_RXCMD2TRNTRM)
#define ADI_C2CC_READ_SWBCKCLK(base)    ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM4, ADI_C2CC_BITP_SWBCKCLK, ADI_C2CC_BITM_SWBCKCLK)
#define ADI_C2CC_READ_SWBCKTRM(base)    ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM5, ADI_C2CC_BITP_SWBCKTRM, ADI_C2CC_BITM_SWBCKTRM)
#define ADI_C2CC_READ_TRAINPOLY_LFSR_POLY(base, lane, edge)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPOLY(lane, edge), ADI_C2CC_BITP_LFSR_POLY, ADI_C2CC_BITM_LFSR_POLY)
#define ADI_C2CC_READ_TRAINPOLY_LFSR_SEED(base, lane, edge)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPOLY(lane, edge), ADI_C2CC_BITP_LFSR_SEED, ADI_C2CC_BITM_LFSR_SEED)
#define ADI_C2CC_READ_TRAINSTAT1_FAIL_CNT(base, lane, edge)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINSTAT1(lane, edge), ADI_C2CC_BITP_CAL_FAIL_CNT, ADI_C2CC_BITM_CAL_FAIL_CNT)
#define ADI_C2CC_READ_TRAINSTAT1_LATE_CNT(base, lane, edge)     ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINSTAT1(lane, edge), ADI_C2CC_BITP_CAL_LATE_CNT, ADI_C2CC_BITM_CAL_LATE_CNT)
#define ADI_C2CC_READ_TRAINSTAT2_BAD_CNT(base, lane, edge)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINSTAT2(lane, edge), ADI_C2CC_BITP_CAL_BAD_CNT, ADI_C2CC_BITM_CAL_BAD_CNT)
#define ADI_C2CC_READ_TRAINSTAT2_EARLY_CNT(base, lane, edge)    ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINSTAT2(lane, edge), ADI_C2CC_BITP_CAL_EARLY_CNT, ADI_C2CC_BITM_CAL_EARLY_CNT)
#define ADI_C2CC_READ_TRAINSTAT3_RAW(base)      ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINSTAT3, 0, 0xFFFFFFFF)
#define ADI_C2CC_READ_TRAIN_DEV_TX_CLK_DIV(base)        ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CLKCTRL2, ADI_C2CC_BITP_TRAIN_DEV_TX_CLK_DIV, ADI_C2CC_BITM_TRAIN_DEV_TX_CLK_DIV)
#define ADI_C2CC_READ_TRAIN_PLL_TX_CLK_DIV(base)        ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CLKCTRL2, ADI_C2CC_BITP_TRAIN_PLL_TX_CLK_DIV, ADI_C2CC_BITM_TRAIN_PLL_TX_CLK_DIV)
#define ADI_C2CC_READ_TRAIN_ROSC_TX_CLK_DIV(base)       ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_CLKCTRL2, ADI_C2CC_BITP_TRAIN_ROSC_TX_CLK_DIV, ADI_C2CC_BITM_TRAIN_ROSC_TX_CLK_DIV)
#define ADI_C2CC_READ_TXCALDONE(base)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM6, ADI_C2CC_BITP_TXCALDONE, ADI_C2CC_BITM_TXCALDONE)
#define ADI_C2CC_READ_TXCLKSW2PTRN(base)        ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM5, ADI_C2CC_BITP_TXCLKSW2PTRN, ADI_C2CC_BITM_TXCLKSW2PTRN)
#define ADI_C2CC_READ_TXPTRNDUR(base)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_TRAINPARAM6, ADI_C2CC_BITP_TXPTRNDUR, ADI_C2CC_BITM_TXPTRNDUR)
#define ADI_C2CC_READ_TXDATA_DELAY(base, lane)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_DLYTRIM2, ADI_C2CC_BITP_TXDATA_DELAY(lane), ADI_C2CC_BITM_TXDATA_DELAY(lane))
#define ADI_C2CC_READ_RXDATA_DELAY(base, lane)   ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_DLYTRIM2, ADI_C2CC_BITP_RXDATA_DELAY(lane), ADI_C2CC_BITM_RXDATA_DELAY(lane))

/* write macros */
#define ADI_C2CC_WRITE_AXI_INIT_EN(base, val)   ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CONFIG, ADI_C2CC_BITP_AXI_INIT_EN, ADI_C2CC_BITM_AXI_INIT_EN, (val))
#define ADI_C2CC_WRITE_BF32     adi_c2cc_write_bf32
#define ADI_C2CC_WRITE_BLKTRF(base, val)        ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM1, ADI_C2CC_BITP_BLKTRF, ADI_C2CC_BITM_BLKTRF, (val))
#define ADI_C2CC_WRITE_C2C_EN(base, val)        ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CONFIG, ADI_C2CC_BITP_C2C_EN, ADI_C2CC_BITM_C2C_EN, (val))
#define ADI_C2CC_WRITE_CHECKPOLY_LFSR_POLY(base, lane, edge, val)       ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CHECKPOLY(lane, edge), ADI_C2CC_BITP_LFSR_POLY_CHECK, ADI_C2CC_BITM_LFSR_POLY_CHECK, (val))
#define ADI_C2CC_WRITE_CMD2TXCLKSW(base, val)   ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM1, ADI_C2CC_BITP_CMD2TXCLKSW, ADI_C2CC_BITM_CMD2TXCLKSW, (val))
#define ADI_C2CC_WRITE_DEV_TX_CLK_DIV(base, val)        ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CLKCTRL1, ADI_C2CC_BITP_DEV_TX_CLK_DIV, ADI_C2CC_BITM_DEV_TX_CLK_DIV, (val))
#define ADI_C2CC_WRITE_INT_EN(base, val)        ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CONFIG, ADI_C2CC_BITP_INT_EN, ADI_C2CC_BITM_INT_EN, (val))
#define ADI_C2CC_WRITE_LDDUR(base, val) ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM2, ADI_C2CC_BITP_LDDUR, ADI_C2CC_BITM_LDDUR, (val))
#define ADI_C2CC_WRITE_MTCHDUR(base, val)       ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM2, ADI_C2CC_BITP_MTCHDUR, ADI_C2CC_BITM_MTCHDUR, (val))
#define ADI_C2CC_WRITE_PLL_TX_CLK_DIV(base, val)        ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CLKCTRL1, ADI_C2CC_BITP_PLL_TX_CLK_DIV, ADI_C2CC_BITM_PLL_TX_CLK_DIV, (val))
#define ADI_C2CC_WRITE_POWERUP_CAL_START(base, val)     ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CALIBCTRL1, ADI_C2CC_BITP_POWERUP_CAL_START, ADI_C2CC_BITM_POWERUP_CAL_START, (val))
#define ADI_C2CC_WRITE_PWR_UP_RX_CAL_IRQ(base, val)     ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_INT_STATUS, ADI_C2CC_BITP_PWR_UP_RX_CAL_IRQ, ADI_C2CC_BITM_PWR_UP_RX_CAL_IRQ, (val))
#define ADI_C2CC_WRITE_PWR_UP_TX_CAL_IRQ(base, val)     ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_INT_STATUS, ADI_C2CC_BITP_PWR_UP_TX_CAL_IRQ, ADI_C2CC_BITM_PWR_UP_TX_CAL_IRQ, (val))
#define ADI_C2CC_WRITE_RESP2CMD(base, val)      ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM3, ADI_C2CC_BITP_RESP2CMD, ADI_C2CC_BITM_RESP2CMD, (val))
#define ADI_C2CC_WRITE_ROSC_TX_CLK_DIV(base, val)       ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CLKCTRL1, ADI_C2CC_BITP_ROSC_TX_CLK_DIV, ADI_C2CC_BITM_ROSC_TX_CLK_DIV, (val))
#define ADI_C2CC_WRITE_RXCLK_DELAY(base, val)   ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_DLYTRIM1, ADI_C2CC_BITP_RXCLK_DELAY, ADI_C2CC_BITM_RXCLK_DELAY, (val))
#define ADI_C2CC_WRITE_RXCLK_DELAY_TRAIN(base, val)     ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_DLYTRIM4, ADI_C2CC_BITP_RXCLK_DELAY_TRAIN, ADI_C2CC_BITM_RXCLK_DELAY_TRAIN, (val))
#define ADI_C2CC_WRITE_RXCMD2LD(base, val)      ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM3, ADI_C2CC_BITP_RXCMD2LD, ADI_C2CC_BITM_RXCMD2LD, (val))
#define ADI_C2CC_WRITE_RXCMD2TRNTRM(base, val)  ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM4, ADI_C2CC_BITP_RXCMD2TRNTRM, ADI_C2CC_BITM_RXCMD2TRNTRM, (val))
#define ADI_C2CC_WRITE_SWBCKCLK(base, val)      ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM4, ADI_C2CC_BITP_SWBCKCLK, ADI_C2CC_BITM_SWBCKCLK, (val))
#define ADI_C2CC_WRITE_SWBCKTRM(base, val)      ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM5, ADI_C2CC_BITP_SWBCKTRM, ADI_C2CC_BITM_SWBCKTRM, (val))
#define ADI_C2CC_WRITE_TRAINPOLY_LFSR_POLY(base, lane, edge, val)       ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPOLY(lane, edge), ADI_C2CC_BITP_LFSR_POLY, ADI_C2CC_BITM_LFSR_POLY, (val))
#define ADI_C2CC_WRITE_TRAINPOLY_LFSR_SEED(base, lane, edge, val)       ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPOLY(lane, edge), ADI_C2CC_BITP_LFSR_SEED, ADI_C2CC_BITM_LFSR_SEED, (val))
#define ADI_C2CC_WRITE_TRAIN_DEV_TX_CLK_DIV(base, val)  ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CLKCTRL2, ADI_C2CC_BITP_TRAIN_DEV_TX_CLK_DIV, ADI_C2CC_BITM_TRAIN_DEV_TX_CLK_DIV, (val))
#define ADI_C2CC_WRITE_TRAIN_PLL_TX_CLK_DIV(base, val)  ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CLKCTRL2, ADI_C2CC_BITP_TRAIN_PLL_TX_CLK_DIV, ADI_C2CC_BITM_TRAIN_PLL_TX_CLK_DIV, (val))
#define ADI_C2CC_WRITE_TRAIN_ROSC_TX_CLK_DIV(base, val) ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_CLKCTRL2, ADI_C2CC_BITP_TRAIN_ROSC_TX_CLK_DIV, ADI_C2CC_BITM_TRAIN_ROSC_TX_CLK_DIV, (val))
#define ADI_C2CC_WRITE_TXCALDONE(base, val)     ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM6, ADI_C2CC_BITP_TXCALDONE, ADI_C2CC_BITM_TXCALDONE, (val))
#define ADI_C2CC_WRITE_TXCLKSW2PTRN(base, val)  ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM5, ADI_C2CC_BITP_TXCLKSW2PTRN, ADI_C2CC_BITM_TXCLKSW2PTRN, (val))
#define ADI_C2CC_WRITE_TXPTRNDUR(base, val)     ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_TRAINPARAM6, ADI_C2CC_BITP_TXPTRNDUR, ADI_C2CC_BITM_TXPTRNDUR, (val))
#define ADI_C2CC_WRITE_TXDATA_DELAY(base, lane, val)   ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_DLYTRIM2, ADI_C2CC_BITP_TXDATA_DELAY(lane), ADI_C2CC_BITM_TXDATA_DELAY(lane), (val))
#define ADI_C2CC_WRITE_RXDATA_DELAY(base, lane, val)   ADI_C2CC_WRITE_BF32((base) + ADI_C2CC_REG_DLYTRIM2, ADI_C2CC_BITP_RXDATA_DELAY(lane), ADI_C2CC_BITM_RXDATA_DELAY(lane), (val))

/* helper macros */
#define ADI_C2CC_GET_EDGE_STAT(reg, lane, edge) ((reg) >> ((((lane) * 8) + ((edge) * 4)) & 0xF))
#define ADI_C2CC_IS_AXI_OUTSTANDING(base)       (ADI_C2CC_READ_BF32((base) + ADI_C2CC_REG_OTSTS, ADI_C2CC_BITP_AXI_OUTSTANDING, ADI_C2CC_BITM_AXI_OUTSTANDING) == 0 ? false : true)

#endif /* __ADI_C2CC_INTERNAL_H__ */
