/*
 * Copyright (c) 2024, Analog Devices Incorporated, All Rights Reserved
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __ADI_OTP_INTERNAL_H__
#define __ADI_OTP_INTERNAL_H__


/* register definitions */
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL  0x00000000U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_IDLE_STATUS      0x00000004U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ  0x00000038U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ2     0x00000150U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_ADDR     0x00000044U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ       0x0000009CU
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_DATA      0x000000B0U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC       0x000000B4U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ      0x00000144U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ0     0x00000148U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ1     0x0000014CU
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ      0x00000130U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ0     0x00000134U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ1     0x00000138U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ2     0x0000013CU
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ  0x00000020U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC      0x00000140U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_REDN     0x00000040U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_REQ  0x00000048U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA    0x00000158U
#define IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_STATUS       0x00000060U
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL(base)   ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_IDLE_STATUS(base)       ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_IDLE_STATUS))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ(base)   ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ2(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ2))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_ADDR(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_ADDR))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ(base)        ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_DATA(base)       ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_DATA))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC(base)        ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ(base)       ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ0(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ0))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ1(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ1))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ(base)       ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ0(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ0))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ1(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ1))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ2(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ2))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ(base)   ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC(base)       ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_REDN(base)      ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_REDN))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_REQ(base)   ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_REQ))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA(base)     ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA))
#define pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_STATUS(base)        ((volatile uint32_t *)((base) + IDX_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_STATUS))

/* bitfield definitions */
#define BITM_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI     0x1U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_EN_USER     0x2U
#define BITM_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR    0x10U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_STATUS_IDLE 0x1U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ       0x1U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ       0x4U
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_10     0xFF0000U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_ADDR        0xFFFFFFFFU
#define BITM_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ  0x1U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_BYPASS       0x10000U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_DISABLE      0x20000U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_GEN  0x40000U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_TEST 0x80000U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_DATA     0xFFFFFFFFU
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_NO_ERR_FLAG      0x100U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_SEC_FLAG 0x200U
#define BITM_MEM_CTRL_REGMAP_MC_OTP_RD_DED_FLAG 0x400U
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ_REGS_0      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_0      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_4      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_8      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ_REGS_0      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_0      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_4      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_8      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ       0x1U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ       0x4U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ       0x10U
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC_REGS_0      0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_CMD_REDN        0x3U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_ECC_GEN 0x80U
#define BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA_REGS_0    0xFFU
#define BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ     0x1U
#define BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_STATUS_0        0xFFU
#define BITP_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI     0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_EN_USER     1U
#define BITP_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR    4U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_STATUS_IDLE 0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ       0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ       2U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_10     16U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_ADDR        0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ  0U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_BYPASS       16U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_DISABLE      17U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_GEN  18U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_TEST 19U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_DATA     0U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC      0U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_NO_ERR_FLAG      8U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_SEC_FLAG 9U
#define BITP_MEM_CTRL_REGMAP_MC_OTP_RD_DED_FLAG 10U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ_REGS_0      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_0      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_4      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_8      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ_REGS_0      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_0      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_4      0U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_8      0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ       0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ       2U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ       4U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC_REGS_0      0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_REDN        0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_ECC_GEN 7U
#define BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA_REGS_0    0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ     0U
#define BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_STATUS_0        0U

/* read / write macros */
#define READ_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI(base)       READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI, BITM_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI)
#define READ_MEM_CTRL_REGMAP_MC_CMD_EN_USER(base)       READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_EN_USER, BITM_MEM_CTRL_REGMAP_MC_CMD_EN_USER)
#define READ_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR(base)      READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL((base)), BITP_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR, BITM_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR)
#define READ_MEM_CTRL_REGMAP_MC_CMD_STATUS_IDLE(base)   READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_IDLE_STATUS((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_STATUS_IDLE, BITM_MEM_CTRL_REGMAP_MC_CMD_STATUS_IDLE)
#define READ_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ(base) READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ)
#define READ_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ(base) READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ)
#define READ_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ(base)    READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ)
#define READ_MEM_CTRL_REGMAP_MC_OTP_RD_DATA(base)       READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_DATA((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_DATA, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_DATA)
#define READ_MEM_CTRL_REGMAP_MC_OTP_RD_ECC(base)        READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC)
#define READ_MEM_CTRL_REGMAP_MC_OTP_RD_NO_ERR_FLAG(base)        READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_NO_ERR_FLAG, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_NO_ERR_FLAG)
#define READ_MEM_CTRL_REGMAP_MC_OTP_RD_SEC_FLAG(base)   READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_SEC_FLAG, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_SEC_FLAG)
#define READ_MEM_CTRL_REGMAP_MC_OTP_RD_DED_FLAG(base)   READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_DED_FLAG, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_DED_FLAG)
#define READ_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ(base) READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ)
#define READ_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ(base) READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ)
#define READ_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ(base) READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ)
#define READ_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ(base)       READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ)
#define READ_MEM_CTRL_REGMAP_MC_CMD_PGM_STATUS_0(base)  READ_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_STATUS((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_STATUS_0, BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_STATUS_0)
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI(base, val) WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI, BITM_MEM_CTRL_REGMAP_MC_CMD_EN_SBPI, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_EN_USER(base, val) WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_EN_USER, BITM_MEM_CTRL_REGMAP_MC_CMD_EN_USER, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR(base, val)        WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_EN_CTRL((base)), BITP_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR, BITM_MEM_CTRL_REGMAP_MC_LOAD_QSR_QRR, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ(base, val)   WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_RQ_REQ, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ(base, val)   WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_DAP_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_DAP_CQ_REQ, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_10(base, val) WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ2((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_10, BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_10, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_ADDR(base, val)    WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_ADDR((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_ADDR, BITM_MEM_CTRL_REGMAP_MC_CMD_ADDR, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ(base, val)      WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_OTP_RD_REQ, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_BYPASS(base, val)   WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_BYPASS, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_BYPASS, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_DISABLE(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_DISABLE, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_DISABLE, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_GEN(base, val)      WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_GEN, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_GEN, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_TEST(base, val)     WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_OTP_RD_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_TEST, BITM_MEM_CTRL_REGMAP_MC_OTP_RD_ECC_TEST, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ_REGS_0(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ_REGS_0, BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_CQ_REGS_0, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_0(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ0((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_0, BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_0, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_4(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ1((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_4, BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_4, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_8(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ2((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_8, BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_RQ_REGS_8, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ_REGS_0(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ_REGS_0, BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_CQ_REGS_0, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_0(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ0((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_0, BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_0, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_4(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ1((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_4, BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_4, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_8(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ2((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_8, BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_RQ_REGS_8, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ(base, val)   WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_RQ_REQ, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ(base, val)   WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CQ_REQ, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ(base, val)   WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PMC_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_WR_PMC_CC_REQ, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC_REGS_0(base, val)  WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC_REGS_0, BITM_MEM_CTRL_REGMAP_MC_SBPI_PMC_CC_REGS_0, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_REDN(base, val)    WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_REDN((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_REDN, BITM_MEM_CTRL_REGMAP_MC_CMD_REDN, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_PGM_ECC_GEN(base, val)     WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_ECC_GEN, BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_ECC_GEN, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA_REGS_0(base, val)        WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA((base)), BITP_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA_REGS_0, BITM_MEM_CTRL_REGMAP_MC_SBPI_DAP_DATA_REGS_0, ((val)))
#define WRITE_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ(base, val) WRITE_BF_32BIT_REG(pREG_MEM_CTRL_REGMAP_MEM_CTRL_REGMAP_MC_PGM_REQ((base)), BITP_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ, BITM_MEM_CTRL_REGMAP_MC_CMD_PGM_REQ, ((val)))


#endif /* __ADI_OTP_INTERNAL_H__ */
