/*
 * Copyright (c) 2023, Analog Devices Incorporated - All Rights Reserved
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef ADRV906X_GICV3_DEF_H
#define ADRV906X_GICV3_DEF_H

#include <adrv906x_irq_def.h>
#include <common/interrupt_props.h>
#include <drivers/arm/gicv3.h>

/*
 * Define a list of Group 1 Secure and Group 0 interrupt properties as per GICv3
 * terminology.
 */

/* If you need to turn off EL3_EXCEPTION_HANDLING, remove INTR_PROP_DESC(ADI_SDEI_SGI_PRIVATE, PLAT_SDEI_NORMAL_PRI, INTR_GROUP0, GIC_INTR_CFG_EDGE) from the list below.*/

#define PLAT_IRQ_PROPS \
	INTR_PROP_DESC(ADI_SDEI_SGI_PRIVATE, PLAT_SDEI_NORMAL_PRI, INTR_GROUP0, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_L4_ECC_ERR_INTR_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_L4_ECC_ERR_INTR_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_L4_ECC_ERR_INTR_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_L4_ECC_WRN_INTR_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_L4_ECC_WRN_INTR_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_L4_ECC_WRN_INTR_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NCNTPSIRQ_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NCNTPSIRQ_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NCNTPSIRQ_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NCNTPSIRQ_3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NERRIRQ_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NERRIRQ_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NERRIRQ_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NERRIRQ_3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NERRIRQ_4, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NFAULTIRQ_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NFAULTIRQ_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NFAULTIRQ_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NFAULTIRQ_3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_NFAULTIRQ_4, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_WATCHDOG_A55_TIMEOUT_PIPED_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_WATCHDOG_A55_TIMEOUT_PIPED_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_WATCHDOG_A55_TIMEOUT_PIPED_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_WATCHDOG_A55_TIMEOUT_PIPED_3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_C2C_NON_CRIT_INTR, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_CRIT_INTR, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_ECC_CORRECTED_ERR_INTR, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_ECC_CORRECTED_ERR_INTR_FAULT, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_O_ECC_UNCORRECTED_ERR_INTR, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_O_ECC_UNCORRECTED_ERR_INTR_FAULT, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_O_ECC_AP_ERR_INTR, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_O_ECC_AP_ERR_INTR_FAULT, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GP_INTERRUPT_SYNC_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_PL011_UART_INTR_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_SPU_IRQ0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_SPU_IRQ1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_SPU_IRQ2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_SPU_IRQ3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_SPU_IRQ4, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TE_HREQ_ACK_IRQ_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TE_ERESP_RDY_IRQ_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TE_FAULT_GP_INTR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TE_H_HINF_IRQ_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_24, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_25, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_26, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_27, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_28, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_29, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_30, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPIO_TO_GIC_SYNC_31, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_17, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_18, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_20, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_21, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_23, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_24, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_223, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_224, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_225, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_226, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_227, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_228, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_229, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_C2C_OUT_HW_INTERRUPT_230, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TZCINT_DDR, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TZCINT_L4_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TZCINT_L4_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_TZCINT_L4_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \
	INTR_PROP_DESC(IRQ_GPINT_INTERRUPT_SECONDARY_TO_PRIMARY, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_LEVEL), \

/* Reserve room for GIC lanes related to the peripherals exposed to the customer:
 * This content is meaningless, just to extend 'interrupt_props' array size
 * for additional GIC lanes configuration
 */
#define PLAT_CONFIGURABLE_IRQ_PROPS  \
	INTR_PROP_DESC(IRQ_PL011_UART_INTR_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_PL011_UART_INTR_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_PL011_UART_INTR_3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_1_RX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_1_TX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_1_TX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_1_RX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_1_ERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_1_STAT_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_2_RX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_2_TX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_2_TX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_2_RX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_2_ERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_2_STAT_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_3_RX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_3_TX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_3_TX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_3_RX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_3_ERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_3_STAT_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_4_RX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_4_TX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_4_TX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_4_RX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_4_ERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_4_STAT_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_5_RX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_5_TX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_5_TX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_5_RX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_5_ERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_5_STAT_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_6_RX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_6_TX_DDEERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_6_TX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_6_RX_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_6_ERR_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_IRQ_SPI_6_STAT_PIPED, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_0, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_1, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_2, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_3, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_4, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_5, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_6, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \
	INTR_PROP_DESC(IRQ_I2C_IRQ_S2F_PIPED_7, PLAT_IRQ_NORMAL_PRIORITY, INTR_GROUP1NS, GIC_INTR_CFG_EDGE), \


#endif /*ADRV906X_GICV3_DEF_H*/
