/*
 * Copyright (c) 2024, Analog Devices Incorporated, All Rights Reserved
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __ADI_ADRV906X_AHB_DEF_H__
#define __ADI_ADRV906X_AHB_DEF_H__

#define CLK_AHB_CONFIG_REG      0x01040
#define CLK_AHB_REG_RD_CYCLES_MASK      0x0000003F
#define CLK_AHB_REG_RD_CYCLES_POS       0
#define CLK_AHB_REG_WR_HOLD_MASK        0x00000FC0
#define CLK_AHB_REG_WR_HOLD_POS 6
#define CLK_AHB_REG_WR_SETUP_MASK       0x0003F000
#define CLK_AHB_REG_WR_SETUP_POS        12
#define CORE_AHB_RD_CYCLES_MASK 0x3F
#define CORE_AHB_RD_CYCLES_POS  0
#define CORE_AHB_RD_CYCLES_REG  0x1BB9
#define CORE_AHB_WR_HOLD_CYCLES_MASK    0x3F
#define CORE_AHB_WR_HOLD_CYCLES_POS     0
#define CORE_AHB_WR_HOLD_CYCLES_REG     0x1BB8
#define CORE_AHB_WR_SETUP_CYCLES_MASK   0x3F
#define CORE_AHB_WR_SETUP_CYCLES_POS    0
#define CORE_AHB_WR_SETUP_CYCLES_REG    0x1BB7
#define ETH_AHB_BRIDGE_ANA_REGS 0x0000
#define ETH_AHB_BRIDGE_REGS     0x0004
#define ETH_AHB_REG_RD_CYCLES_MASK      0x0000003F
#define ETH_AHB_REG_RD_CYCLES_POS       0
#define ETH_AHB_REG_RD_DELAY_MASK       0x0000000F
#define ETH_AHB_REG_RD_DELAY_POS        0
#define ETH_AHB_REG_WR_HOLD_MASK        0x00003F00
#define ETH_AHB_REG_WR_HOLD_POS 8
#define ETH_AHB_REG_WR_SETUP_MASK       0x003F0000
#define ETH_AHB_REG_WR_SETUP_POS        16
#define ORX_AHB_CONFIG_REG      0x0040
#define ORX_AHB_RD_CYCLES_MASK  0x0000003F
#define ORX_AHB_RD_CYCLES_POS   0
#define ORX_AHB_RD_DELAY_MASK   0x003C0000
#define ORX_AHB_RD_DELAY_POS    18
#define ORX_AHB_WR_HOLD_MASK    0x00000FC0
#define ORX_AHB_WR_HOLD_POS     6
#define ORX_AHB_WR_SETUP_MASK   0x0003F000
#define ORX_AHB_WR_SETUP_POS    12
#define RX_AHB_CONFIG_REG       0x0034
#define RX_AHB_RD_CYCLES_MASK   0x0000003F
#define RX_AHB_RD_CYCLES_POS    0
#define RX_AHB_RD_DELAY_MASK    0x0F000000
#define RX_AHB_RD_DELAY_POS     24
#define RX_AHB_WR_HOLD_MASK     0x00003F00
#define RX_AHB_WR_HOLD_POS      8
#define RX_AHB_WR_SETUP_MASK    0x003F0000
#define RX_AHB_WR_SETUP_POS     16
#define TX_AHB_CONFIG_REG       0x006C
#define TX_AHB_RD_CYCLES_MASK   0x0000003F
#define TX_AHB_RD_CYCLES_POS    0
#define TX_AHB_RD_DELAY_MASK    0x003C0000
#define TX_AHB_RD_DELAY_POS     18
#define TX_AHB_WR_HOLD_MASK     0x00000FC0
#define TX_AHB_WR_HOLD_POS      6
#define TX_AHB_WR_SETUP_MASK    0x0003F000
#define TX_AHB_WR_SETUP_POS     12


#endif /* __ADI_ADRV906X_AHB_DEF_H__ */
