/*
 * Copyright (c) 2024, Analog Devices Incorporated, All Rights Reserved
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef __ADI_ADRV906X_PLL_INTERNAL_H__
#define __ADI_ADRV906X_PLL_INTERNAL_H__


/* register definitions */
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0  0x00001658U
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1  0x00001664U
#define IDX_CORE_CLOCK_CONTROL_REGISTERS_CLOCK_CONTROL_2        0x00001019U
#define IDX_CORE_DEVCLK_CONTROL_GROUP_DEVCLK_BUFFER_CONTROL     0x0000162FU
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0    0x00001650U
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1    0x0000165CU
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM0     0x00001657U
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM1     0x00001663U
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM0   0x00001651U
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM1   0x0000165DU
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM0   0x00001653U
#define IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM1   0x0000165FU
#define IDX_CORE_DEVCLK_CONTROL_GROUP_REFCLK_CLKSYNTH_CONTROL   0x00001638U
#define IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD_KILLS 0x00000002U
#define IDX_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV 0x00000073U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_CHARGE_PUMP_CONFIG0       0x0000000AU
#define IDX_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCCTL   0x00000065U
#define IDX_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL0        0x000000B2U
#define IDX_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_CTL_1       0x000000B0U
#define IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD       0x00000001U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1       0x0000001BU
#define IDX_PLL_MEM_MAP_REF_CLK_REG_REF_CLK_BYTE0       0x00000074U
#define IDX_PLL_MEM_MAP_SDM_REGS_MOD0_3 0x00000058U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_3     0x00000092U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL0      0x00000095U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_1     0x00000090U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT  0x00000094U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_4     0x00000093U
#define IDX_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_STAT        0x000000B1U
#define IDX_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL1        0x000000B3U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_00      0x000000B4U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_03      0x000000B7U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MUX_IN       0x000000C1U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET     0x000000B9U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_BIAS_COMP    0x000000C0U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_CTRL    0x000000C3U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_MISC_KILL_SIGNALS     0x0000008AU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2      0x00000020U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1   0x0000001DU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0    0x00000017U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_FINE_BAND   0x0000001EU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0   0x0000001CU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_PFD_CTL0  0x0000000BU
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL1       0x00000088U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0       0x0000000DU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_R1     0x00000014U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_R3     0x00000016U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_CTL_STAT       0x00000011U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CFG        0x000000A7U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL0       0x00000087U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CTL        0x000000A6U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_C1     0x00000013U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_C2     0x00000012U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_C3     0x00000015U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0        0x00000006U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1        0x00000007U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2        0x00000008U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3        0x00000009U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1 0x00000005U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0 0x00000004U
#define IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL3   0x0000006BU
#define IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL4   0x0000006CU
#define IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL0   0x00000068U
#define IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB  0x00000000U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE1      0x0000001FU
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL1      0x00000096U
#define IDX_PLL_MEM_MAP_SERDES_PLL_REGS_PLUS_TEMP_SENSOR_SERDES_OUTPUT_DIVIDER_CTL      0x000000AEU
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL2      0x00000097U
#define IDX_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0        0x00000066U
#define IDX_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1        0x00000067U
#define IDX_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV     0x00000072U
#define IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_LOGEN_CLKGEN_LOSYNC_PD        0x00000003U
#define IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_MOD_VCO_CAL_CTL        0x00000075U
#define IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_QUICK_FREQ_CAL_CTL     0x00000076U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_LOCKDET_CONFIG    0x00000026U
#define IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0      0x00000077U
#define IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1      0x00000078U
#define IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2      0x00000079U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC     0x0000000FU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE1    0x00000018U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC2    0x00000010U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL2       0x00000089U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_MCS_CONTROL_2     0x00000023U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT1      0x0000008CU
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0      0x0000008BU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL1       0x0000000EU
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE3      0x00000021U
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_TCIDAC_REG0   0x0000009DU
#define IDX_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_1    0x0000006FU
#define IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5   0x0000006DU
#define IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_PRESCALER_CTL 0x0000008DU
#define IDX_PLL_MEM_MAP_SDM_REGS_MOD0_0 0x00000055U
#define IDX_PLL_MEM_MAP_SDM_REGS_MOD0_1 0x00000056U
#define IDX_PLL_MEM_MAP_SDM_REGS_MOD0_2 0x00000057U
#define IDX_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0       0x0000001AU
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01      0x000000B5U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02      0x000000B6U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00        0x000000C7U
#define IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01        0x000000C8U
#define IDX_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_2    0x00000070U
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0(base)   ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1(base)   ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1))
#define pREG_CORE_CLOCK_CONTROL_REGISTERS_CLOCK_CONTROL_2(base) ((volatile uint8_t *)((base) + IDX_CORE_CLOCK_CONTROL_REGISTERS_CLOCK_CONTROL_2))
#define pREG_CORE_DEVCLK_CONTROL_GROUP_DEVCLK_BUFFER_CONTROL(base)      ((volatile uint8_t *)((base) + IDX_CORE_DEVCLK_CONTROL_GROUP_DEVCLK_BUFFER_CONTROL))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0(base)     ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1(base)     ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM0(base)      ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM0))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM1(base)      ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM1))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM0(base)    ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM0))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM1(base)    ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM1))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM0(base)    ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM0))
#define pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM1(base)    ((volatile uint8_t *)((base) + IDX_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM1))
#define pREG_CORE_DEVCLK_CONTROL_GROUP_REFCLK_CLKSYNTH_CONTROL(base)    ((volatile uint8_t *)((base) + IDX_CORE_DEVCLK_CONTROL_GROUP_REFCLK_CLKSYNTH_CONTROL))
#define pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD_KILLS(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD_KILLS))
#define pREG_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_CHARGE_PUMP_CONFIG0(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_CHARGE_PUMP_CONFIG0))
#define pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCCTL(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCCTL))
#define pREG_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL0(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL0))
#define pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_CTL_1(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_CTL_1))
#define pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1))
#define pREG_PLL_MEM_MAP_REF_CLK_REG_REF_CLK_BYTE0(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_REF_CLK_REG_REF_CLK_BYTE0))
#define pREG_PLL_MEM_MAP_SDM_REGS_MOD0_3(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SDM_REGS_MOD0_3))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_3(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_3))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL0(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL0))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_1(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_1))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT(base)   ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_4(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_4))
#define pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_STAT(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_STAT))
#define pREG_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL1(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL1))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_00(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_00))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_03(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_03))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MUX_IN(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MUX_IN))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_BIAS_COMP(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_BIAS_COMP))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_CTRL(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_CTRL))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_MISC_KILL_SIGNALS(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_MISC_KILL_SIGNALS))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_FINE_BAND(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_FINE_BAND))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_PFD_CTL0(base)   ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_PFD_CTL0))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL1(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_R1(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_R1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_R3(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_R3))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_CTL_STAT(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_CTL_STAT))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CFG(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CFG))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL0(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL0))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CTL(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CTL))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C1(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_C1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C2(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_C2))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C3(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_LF_C3))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0))
#define pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL3(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL3))
#define pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL4(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL4))
#define pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL0(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL0))
#define pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB(base)   ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE1(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE1))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL1(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL1))
#define pREG_PLL_MEM_MAP_SERDES_PLL_REGS_PLUS_TEMP_SENSOR_SERDES_OUTPUT_DIVIDER_CTL(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SERDES_PLL_REGS_PLUS_TEMP_SENSOR_SERDES_OUTPUT_DIVIDER_CTL))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL2(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL2))
#define pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0))
#define pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1))
#define pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV))
#define pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_LOGEN_CLKGEN_LOSYNC_PD(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PD_EN_RESETB_REGS_LOGEN_CLKGEN_LOSYNC_PD))
#define pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_MOD_VCO_CAL_CTL(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_MOD_VCO_CAL_CTL))
#define pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_QUICK_FREQ_CAL_CTL(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_QUICK_FREQ_CAL_CTL))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_LOCKDET_CONFIG(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_LOCKDET_CONFIG))
#define pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0))
#define pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1))
#define pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE1(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC2(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC2))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL2(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL2))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_MCS_CONTROL_2(base)      ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_MCS_CONTROL_2))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT1(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT1))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL1(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL1))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE3(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE3))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_TCIDAC_REG0(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_TCIDAC_REG0))
#define pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_1(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_1))
#define pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5(base)    ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5))
#define pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_PRESCALER_CTL(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_NEW_PLL_BASE_REGS_PRESCALER_CTL))
#define pREG_PLL_MEM_MAP_SDM_REGS_MOD0_0(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SDM_REGS_MOD0_0))
#define pREG_PLL_MEM_MAP_SDM_REGS_MOD0_1(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SDM_REGS_MOD0_1))
#define pREG_PLL_MEM_MAP_SDM_REGS_MOD0_2(base)  ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_SDM_REGS_MOD0_2))
#define pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0(base)        ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02(base)       ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00))
#define pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01(base) ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01))
#define pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_2(base)     ((volatile uint8_t *)((base) + IDX_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_2))

/* bitfield definitions */
#define BITM_CORE_MBIAS_IGEN_PTATR_TRIM_DONE    0x40U
#define BITM_CORE_MBIAS_IGEN_PTATR_CODE_RB      0x3FU
#define BITM_CORE_MBIAS_CAL_TRIGGER     0x40U
#define BITM_CORE_DIG_CORE_DEVCLK_PD    0x8U
#define BITM_CORE_MBIAS_IGEN_PD 0x1U
#define BITM_CORE_MBIAS_TRIM_COMP_PD    0x2U
#define BITM_CORE_MBIAS_RTRIM_RESETB    0x10U
#define BITM_CORE_MBIAS_BG_CTAT 0xFU
#define BITM_CORE_MBIAS_BG_PTAT 0x3FU
#define BITM_CORE_DEVCLK_BUFFER_ENABLE  0x1U
#define BITM_CORE_CLKPLL_REFPATH_PD     0x1U
#define BITM_PLL_MEM_MAP_CLKOUT_BUF_PD  0x8U
#define BITM_PLL_MEM_MAP_TEST_CLKDIV_RSTB       0x1U
#define BITM_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK     0x2U
#define BITM_PLL_MEM_MAP_VT_FORCE       0x40U
#define BITM_PLL_MEM_MAP_TCFORCEN       0x1U
#define BITM_PLL_MEM_MAP_SLDO0P8_PD     0x1U
#define BITM_PLL_MEM_MAP_SLDO1P0_RAMP   0x8U
#define BITM_PLL_MEM_MAP_SLDO1P0_PD     0x4U
#define BITM_PLL_MEM_MAP_VCO_LDO_PD     0x1U
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC    0x7U
#define BITM_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO   0x3FU
#define BITM_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0   0xFFU
#define BITM_PLL_MEM_MAP_VCO_LDO_OUTPUT_PD      0x80U
#define BITM_PLL_MEM_MAP_VCOLCR_PD      0x4U
#define BITM_PLL_MEM_MAP_LDO_VOUT_ADJ   0x1FU
#define BITM_PLL_MEM_MAP_LDO_POWERGOOD  0x8U
#define BITM_PLL_MEM_MAP_LDO_CLEAR_STATUS       0x10U
#define BITM_PLL_MEM_MAP_LDO_UVL        0x20U
#define BITM_PLL_MEM_MAP_LDO_CURLIM     0x2U
#define BITM_PLL_MEM_MAP_LDO_LOWOUTPUT  0x40U
#define BITM_PLL_MEM_MAP_LDO_OVERVOLT   0x1U
#define BITM_PLL_MEM_MAP_LDO_THERMSDN   0x4U
#define BITM_PLL_MEM_MAP_LDO_NOREF      0x10U
#define BITM_PLL_MEM_MAP_SLDO1P0_UVFLAG 0x2U
#define BITM_PLL_MEM_MAP_SLDO1P0_OVFLAG 0x1U
#define BITM_PLL_MEM_MAP_PORB_0P8       0x80U
#define BITM_PLL_MEM_MAP_TEMPS_START_MEASUREMENT        0x2U
#define BITM_PLL_MEM_MAP_TEMPS_OFFSET_ADJ       0x7FU
#define BITM_PLL_MEM_MAP_TEMPS_RESET    0x1U
#define BITM_PLL_MEM_MAP_TEMPS_SEL_MUX_VP       0x7U
#define BITM_PLL_MEM_MAP_TEMPS_CLK_PD   0x1U
#define BITM_PLL_MEM_MAP_TEMPS_PTAT_PD  0x4U
#define BITM_PLL_MEM_MAP_TEMPS_REF_PD   0x8U
#define BITM_PLL_MEM_MAP_TEMPS_ADC_PD   0x10U
#define BITM_PLL_MEM_MAP_TEMPS_STARTUP_PD       0x2U
#define BITM_PLL_MEM_MAP_TEMPS_CURR_FLASHO_N    0xFU
#define BITM_PLL_MEM_MAP_TEMPS_WAIT_TO_MEASURE  0x1CU
#define BITM_PLL_MEM_MAP_TEMPS_WAKE_SETTING     0xE0U
#define BITM_PLL_MEM_MAP_TEMPS_RESET_ADC        0x80U
#define BITM_PLL_MEM_MAP_KILLRDIV_VCOCAL        0x40U
#define BITM_PLL_MEM_MAP_VCOBUF_TO_PS_PD        0x2U
#define BITM_PLL_MEM_MAP_VCO_TC_TRACKING_EN     0x1U
#define BITM_PLL_MEM_MAP_VCO_F_COARSE_BAND_EN   0x2U
#define BITM_PLL_MEM_MAP_VCO_FINE_CAL_EN        0x8U
#define BITM_PLL_MEM_MAP_VCO_F_FINE_BAND_EN     0x40U
#define BITM_PLL_MEM_MAP_VCO_F_FINE_BAND        0x3FU
#define BITM_PLL_MEM_MAP_VCO_CAL_INIT   0x1U
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND        0x1U
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND        0xFFU
#define BITM_PLL_MEM_MAP_VCO_COARSE_CAL_EN      0x80U
#define BITM_PLL_MEM_MAP_PFD_KILLUPDN   0xC0U
#define BITM_PLL_MEM_MAP_CP_I   0x1FU
#define BITM_PLL_MEM_MAP_CP_IBLEED      0x7FU
#define BITM_PLL_MEM_MAP_CP_CAL_CLK_DIVIDE      0x70U
#define BITM_PLL_MEM_MAP_CP_CAL_INIT    0x1U
#define BITM_PLL_MEM_MAP_LF_BYPASS_R1   0x40U
#define BITM_PLL_MEM_MAP_LF_BYPASS_R3   0x40U
#define BITM_PLL_MEM_MAP_CP_SEL_ADC_TC  0x8U
#define BITM_PLL_MEM_MAP_CP_CAL_EN      0x2U
#define BITM_PLL_MEM_MAP_BLEED_RAMP_STEP        0xFU
#define BITM_PLL_MEM_MAP_BLEED_RAMP_TIME_STEP   0xF0U
#define BITM_PLL_MEM_MAP_CP_BLEED_DN_EN 0x4U
#define BITM_PLL_MEM_MAP_CP_BLEED_UP_EN 0x8U
#define BITM_PLL_MEM_MAP_BLEED_RAMP_EN  0x1U
#define BITM_PLL_MEM_MAP_BLEED_RAMP_INIT        0x2U
#define BITM_PLL_MEM_MAP_LF_C1  0x3FU
#define BITM_PLL_MEM_MAP_LF_C2  0x3FU
#define BITM_PLL_MEM_MAP_LF_C3  0x3FU
#define BITM_PLL_MEM_MAP_LF_R1  0x3FU
#define BITM_PLL_MEM_MAP_LF_R3  0x3FU
#define BITM_PLL_MEM_MAP_LF_BYPASS_C1   0x40U
#define BITM_PLL_MEM_MAP_LF_BYPASS_C2   0x40U
#define BITM_PLL_MEM_MAP_VCO_TC_WAIT    0x70U
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0_SDM_FRAC      0xFFU
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1_SDM_FRAC      0xFFU
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2_SDM_FRAC      0xFFU
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3_SDM_FRAC      0xFFU
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1_SDM_INT        0x7U
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0_SDM_INT        0xFFU
#define BITM_PLL_MEM_MAP_LODIV_RB       0x10U
#define BITM_PLL_MEM_MAP_LODIV_FUND     0x2U
#define BITM_PLL_MEM_MAP_LODIV_THERMCODE        0x3FU
#define BITM_PLL_MEM_MAP_VCO_F_ALC_EN   0x80U
#define BITM_PLL_MEM_MAP_VCO_CAL_LOGIC_RESETB   0x1U
#define BITM_PLL_MEM_MAP_VCO_SEL        0x3U
#define BITM_PLL_MEM_MAP_LDO_VPTATCTRL  0x60U
#define BITM_PLL_MEM_MAP_VCO_VAR_TC     0x1FU
#define BITM_PLL_MEM_MAP_VCO_VAR        0xFU
#define BITM_PLL_MEM_MAP_SERDES_PLL_ODIV        0xFCU
#define BITM_PLL_MEM_MAP_SERDES_PLL_ODIV_KILLCLK        0x1U
#define BITM_PLL_MEM_MAP_VCOPKDET_CM_SEL        0xF0U
#define BITM_PLL_MEM_MAP_VCOPKDET_VREF_SEL      0xFU
#define BITM_PLL_MEM_MAP_VCOPKDET_BYP_RES_DET   0x20U
#define BITM_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0_TCIDAC        0xFFU
#define BITM_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1_TCIDAC        0xFU
#define BITM_PLL_MEM_MAP_TCUPDINIT      0x2U
#define BITM_PLL_MEM_MAP_ROOT_CLKDIV_DIV2       0x20U
#define BITM_PLL_MEM_MAP_ROOT_CLKDIV_FUND       0x10U
#define BITM_PLL_MEM_MAP_CLKGEN_SERDES_OUTBUF_PD        0x1U
#define BITM_PLL_MEM_MAP_FREQ_CAL_CNT_RDSEL     0x40U
#define BITM_PLL_MEM_MAP_QUICK_FREQ_CAL_EN      0x80U
#define BITM_PLL_MEM_MAP_LOCKDET_CNT    0xCU
#define BITM_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0_FREQ_CAL_MAX_CNT    0xFFU
#define BITM_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1_FREQ_CAL_MAX_CNT    0xFFU
#define BITM_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2_FREQ_CAL_MAX_CNT    0xFFU
#define BITM_PLL_MEM_MAP_CP_VLEVEL_LOW_TC       0xFU
#define BITM_PLL_MEM_MAP_CP_VLEVEL_HIGH_TC      0xF0U
#define BITM_PLL_MEM_MAP_VCO_CAL_INIT_DEL       0xE0U
#define BITM_PLL_MEM_MAP_VCO_CAL_ALC_INIT_WAIT  0x18U
#define BITM_PLL_MEM_MAP_QUICK_FREQ_CAL_THRESHOLD       0x7FU
#define BITM_PLL_MEM_MAP_VCO_CAL_ALC_CLK_DIV    0x7U
#define BITM_PLL_MEM_MAP_VCO_CAL_ALC_WAIT       0x70U
#define BITM_PLL_MEM_MAP_FORCE_VCO_INIT_ALC_VALUE       0x80U
#define BITM_PLL_MEM_MAP_VCO_ALC_CAL_EN 0x40U
#define BITM_PLL_MEM_MAP_CP_VLEVEL_HIGH_FLAG    0xFU
#define BITM_PLL_MEM_MAP_CP_VLEVEL_LOW_FLAG     0xF0U
#define BITM_PLL_MEM_MAP_CP_AUXADC_HYST_TC      0x3U
#define BITM_PLL_MEM_MAP_CP_AUXADC_HYST_ON_TC   0x4U
#define BITM_PLL_MEM_MAP_AUXADC_HYST_FLAG       0x30U
#define BITM_PLL_MEM_MAP_AUXADC_HYST_ON_FLAG    0x1U
#define BITM_PLL_MEM_MAP_MCS_WAIT_COUNT 0x18U
#define BITM_PLL_MEM_MAP_SEL_ADC_FLAG   0x4U
#define BITM_PLL_MEM_MAP_LDO_SPARE      0xFU
#define BITM_PLL_MEM_MAP_LD_LOL_HYST_EN 0x1U
#define BITM_PLL_MEM_MAP_LD_EN  0x4U
#define BITM_PLL_MEM_MAP_LD_LOL_EN      0x8U
#define BITM_PLL_MEM_MAP_LD_LOL_LDP     0xE0U
#define BITM_PLL_MEM_MAP_LD_COUNT       0x30U
#define BITM_PLL_MEM_MAP_CP_F_CAL       0x40U
#define BITM_PLL_MEM_MAP_CP_F_CAL_BITS  0x3FU
#define BITM_PLL_MEM_MAP_TC_FLAG_STEP   0xF0U
#define BITM_PLL_MEM_MAP_TC_FLAG_STEP_EN        0x2U
#define BITM_PLL_MEM_MAP_SYNTH_PD       0x80U
#define BITM_PLL_MEM_MAP_SDM_PD 0x40U
#define BITM_PLL_MEM_MAP_CP_LEVELDET_PD 0x20U
#define BITM_PLL_MEM_MAP_REF_CLK_DIVIDER_PD     0x10U
#define BITM_PLL_MEM_MAP_PRESCALER_PD   0x4U
#define BITM_PLL_MEM_MAP_VCOTC_DAC_PD   0x2U
#define BITM_PLL_MEM_MAP_VCOTC_I2V_PD   0x8U
#define BITM_PLL_MEM_MAP_LD_PD  0x2U
#define BITM_PLL_MEM_MAP_CP_EN  0x1U
#define BITM_PLL_MEM_MAP_DIGCORE_INTERFACE_KILLCLK      0x40U
#define BITM_PLL_MEM_MAP_DIGCORE_SAMPLE_KILLCLK 0x20U
#define BITM_PLL_MEM_MAP_LO_SYNC_SAMPLER_FLOPS_PD       0x40U
#define BITM_PLL_MEM_MAP_LO_SYNC_SAMPLER_LO_INPUT_BUF_PD        0x80U
#define BITM_PLL_MEM_MAP_ROOT_CLKDIV_RB 0x1U
#define BITM_PLL_MEM_MAP_ROOT_CLKDIV_KILLCLK    0x8U
#define BITM_PLL_MEM_MAP_LO_PHSYNC_QUAD2_KILLCLK        0x40U
#define BITM_PLL_MEM_MAP_LO_PHSYNC_LEAF_KILLCLK 0x10U
#define BITM_PLL_MEM_MAP_SERDES_PLL_ODIV_RB     0x2U
#define BITM_PLL_MEM_MAP_LO_PHSYNC_LEAF_RB      0x20U
#define BITM_PLL_MEM_MAP_LO_PHSYNC_QUAD2_RB     0x80U
#define BITM_PLL_MEM_MAP_DIGCORE_DIV_RSTB       0x80U
#define BITM_PLL_MEM_MAP_REF_CLK_DIVIDER_RESETB 0x80U
#define BITM_PLL_MEM_MAP_PFD_RESETB     0x8U
#define BITM_PLL_MEM_MAP_NDIV_PS_RB     0x2U
#define BITM_PLL_MEM_MAP_LD_RSTB        0x1U
#define BITM_PLL_MEM_MAP_VCOTC_DAC_RST  0x1U
#define BITM_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0   0xFFU
#define BITM_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0   0xFFU
#define BITM_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0   0xFFU
#define BITM_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC    0xFFU
#define BITM_PLL_MEM_MAP_CP_CAL_VALID   0x80U
#define BITM_PLL_MEM_MAP_VCO_CAL_BUSY   0x2U
#define BITM_PLL_MEM_MAP_SYN_LOCK       0x20U
#define BITM_PLL_MEM_MAP_BLEED_RAMP_DONE        0x10U
#define BITM_PLL_MEM_MAP_TEMPS_MEASUREMENT_READY        0x10U
#define BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01_TEMPS_TEMPERATURE   0xFFU
#define BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02_TEMPS_TEMPERATURE   0xFU
#define BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00_TEMPS_CTRL    0xFFU
#define BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01_TEMPS_CTRL    0xFFU
#define BITM_PLL_MEM_MAP_AB_COUNTER_RESETB      0x40U
#define BITM_PLL_MEM_MAP_LOCK_DETECT_RESETB     0x10U
#define BITM_PLL_MEM_MAP_MCS_RESETB     0x8U
#define BITM_PLL_MEM_MAP_LO_SYNC_RESETB 0x4U
#define BITM_PLL_MEM_MAP_DIGCORE_INTDIV_BINCODE 0xFU
#define BITM_PLL_MEM_MAP_DIGCORE_CLKDIV_THERMCODE       0x70U
#define BITM_PLL_MEM_MAP_SDM_RESETB     0x20U
#define BITM_PLL_MEM_MAP_VCO_TC_CAL_RESETB      0x2U
#define BITP_CORE_MBIAS_IGEN_PTATR_TRIM_DONE    6U
#define BITP_CORE_MBIAS_IGEN_PTATR_CODE_RB      0U
#define BITP_CORE_MBIAS_CAL_TRIGGER     6U
#define BITP_CORE_DIG_CORE_DEVCLK_PD    3U
#define BITP_CORE_MBIAS_IGEN_PD 0U
#define BITP_CORE_MBIAS_TRIM_COMP_PD    1U
#define BITP_CORE_MBIAS_RTRIM_RESETB    4U
#define BITP_CORE_MBIAS_BG_CTAT 0U
#define BITP_CORE_MBIAS_BG_PTAT 0U
#define BITP_CORE_DEVCLK_BUFFER_ENABLE  0U
#define BITP_CORE_CLKPLL_REFPATH_PD     0U
#define BITP_PLL_MEM_MAP_CLKOUT_BUF_PD  3U
#define BITP_PLL_MEM_MAP_TEST_CLKDIV_RSTB       0U
#define BITP_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK     1U
#define BITP_PLL_MEM_MAP_VT_FORCE       6U
#define BITP_PLL_MEM_MAP_TCFORCEN       0U
#define BITP_PLL_MEM_MAP_SLDO0P8_PD     0U
#define BITP_PLL_MEM_MAP_SLDO1P0_RAMP   3U
#define BITP_PLL_MEM_MAP_SLDO1P0_PD     2U
#define BITP_PLL_MEM_MAP_VCO_LDO_PD     0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC    0U
#define BITP_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO   0U
#define BITP_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0   0U
#define BITP_PLL_MEM_MAP_VCO_LDO_OUTPUT_PD      7U
#define BITP_PLL_MEM_MAP_VCOLCR_PD      2U
#define BITP_PLL_MEM_MAP_LDO_VOUT_ADJ   0U
#define BITP_PLL_MEM_MAP_LDO_POWERGOOD  3U
#define BITP_PLL_MEM_MAP_LDO_CLEAR_STATUS       4U
#define BITP_PLL_MEM_MAP_LDO_UVL        5U
#define BITP_PLL_MEM_MAP_LDO_CURLIM     1U
#define BITP_PLL_MEM_MAP_LDO_LOWOUTPUT  6U
#define BITP_PLL_MEM_MAP_LDO_OVERVOLT   0U
#define BITP_PLL_MEM_MAP_LDO_THERMSDN   2U
#define BITP_PLL_MEM_MAP_LDO_NOREF      4U
#define BITP_PLL_MEM_MAP_SLDO1P0_UVFLAG 1U
#define BITP_PLL_MEM_MAP_SLDO1P0_OVFLAG 0U
#define BITP_PLL_MEM_MAP_PORB_0P8       7U
#define BITP_PLL_MEM_MAP_TEMPS_START_MEASUREMENT        1U
#define BITP_PLL_MEM_MAP_TEMPS_OFFSET_ADJ       0U
#define BITP_PLL_MEM_MAP_TEMPS_RESET    0U
#define BITP_PLL_MEM_MAP_TEMPS_SEL_MUX_VP       0U
#define BITP_PLL_MEM_MAP_TEMPS_CLK_PD   0U
#define BITP_PLL_MEM_MAP_TEMPS_PTAT_PD  2U
#define BITP_PLL_MEM_MAP_TEMPS_REF_PD   3U
#define BITP_PLL_MEM_MAP_TEMPS_ADC_PD   4U
#define BITP_PLL_MEM_MAP_TEMPS_STARTUP_PD       1U
#define BITP_PLL_MEM_MAP_TEMPS_CURR_FLASHO_N    0U
#define BITP_PLL_MEM_MAP_TEMPS_WAIT_TO_MEASURE  2U
#define BITP_PLL_MEM_MAP_TEMPS_WAKE_SETTING     5U
#define BITP_PLL_MEM_MAP_TEMPS_RESET_ADC        7U
#define BITP_PLL_MEM_MAP_KILLRDIV_VCOCAL        6U
#define BITP_PLL_MEM_MAP_VCOBUF_TO_PS_PD        1U
#define BITP_PLL_MEM_MAP_VCO_TC_TRACKING_EN     0U
#define BITP_PLL_MEM_MAP_VCO_F_COARSE_BAND_EN   1U
#define BITP_PLL_MEM_MAP_VCO_FINE_CAL_EN        3U
#define BITP_PLL_MEM_MAP_VCO_F_FINE_BAND_EN     6U
#define BITP_PLL_MEM_MAP_VCO_F_FINE_BAND        0U
#define BITP_PLL_MEM_MAP_VCO_CAL_INIT   0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND        0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND        0U
#define BITP_PLL_MEM_MAP_VCO_COARSE_CAL_EN      7U
#define BITP_PLL_MEM_MAP_PFD_KILLUPDN   6U
#define BITP_PLL_MEM_MAP_CP_I   0U
#define BITP_PLL_MEM_MAP_CP_IBLEED      0U
#define BITP_PLL_MEM_MAP_CP_CAL_CLK_DIVIDE      4U
#define BITP_PLL_MEM_MAP_CP_CAL_INIT    0U
#define BITP_PLL_MEM_MAP_LF_BYPASS_R1   6U
#define BITP_PLL_MEM_MAP_LF_BYPASS_R3   6U
#define BITP_PLL_MEM_MAP_CP_SEL_ADC_TC  3U
#define BITP_PLL_MEM_MAP_CP_CAL_EN      1U
#define BITP_PLL_MEM_MAP_BLEED_RAMP_STEP        0U
#define BITP_PLL_MEM_MAP_BLEED_RAMP_TIME_STEP   4U
#define BITP_PLL_MEM_MAP_CP_BLEED_DN_EN 2U
#define BITP_PLL_MEM_MAP_CP_BLEED_UP_EN 3U
#define BITP_PLL_MEM_MAP_BLEED_RAMP_EN  0U
#define BITP_PLL_MEM_MAP_BLEED_RAMP_INIT        1U
#define BITP_PLL_MEM_MAP_LF_C1  0U
#define BITP_PLL_MEM_MAP_LF_C2  0U
#define BITP_PLL_MEM_MAP_LF_C3  0U
#define BITP_PLL_MEM_MAP_LF_R1  0U
#define BITP_PLL_MEM_MAP_LF_R3  0U
#define BITP_PLL_MEM_MAP_LF_BYPASS_C1   6U
#define BITP_PLL_MEM_MAP_LF_BYPASS_C2   6U
#define BITP_PLL_MEM_MAP_VCO_TC_WAIT    4U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0_SDM_FRAC      0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1_SDM_FRAC      0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2_SDM_FRAC      0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3_SDM_FRAC      0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1_SDM_INT        0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0_SDM_INT        0U
#define BITP_PLL_MEM_MAP_LODIV_RB       4U
#define BITP_PLL_MEM_MAP_LODIV_FUND     1U
#define BITP_PLL_MEM_MAP_LODIV_THERMCODE        0U
#define BITP_PLL_MEM_MAP_VCO_F_ALC_EN   7U
#define BITP_PLL_MEM_MAP_VCO_CAL_LOGIC_RESETB   0U
#define BITP_PLL_MEM_MAP_VCO_SEL        0U
#define BITP_PLL_MEM_MAP_LDO_VPTATCTRL  5U
#define BITP_PLL_MEM_MAP_VCO_VAR_TC     0U
#define BITP_PLL_MEM_MAP_VCO_VAR        0U
#define BITP_PLL_MEM_MAP_SERDES_PLL_ODIV        2U
#define BITP_PLL_MEM_MAP_SERDES_PLL_ODIV_KILLCLK        0U
#define BITP_PLL_MEM_MAP_VCOPKDET_CM_SEL        4U
#define BITP_PLL_MEM_MAP_VCOPKDET_VREF_SEL      0U
#define BITP_PLL_MEM_MAP_VCOPKDET_BYP_RES_DET   5U
#define BITP_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0_TCIDAC        0U
#define BITP_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1_TCIDAC        0U
#define BITP_PLL_MEM_MAP_TCUPDINIT      1U
#define BITP_PLL_MEM_MAP_ROOT_CLKDIV_DIV2       5U
#define BITP_PLL_MEM_MAP_ROOT_CLKDIV_FUND       4U
#define BITP_PLL_MEM_MAP_CLKGEN_SERDES_OUTBUF_PD        0U
#define BITP_PLL_MEM_MAP_FREQ_CAL_CNT_RDSEL     6U
#define BITP_PLL_MEM_MAP_QUICK_FREQ_CAL_EN      7U
#define BITP_PLL_MEM_MAP_LOCKDET_CNT    2U
#define BITP_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0_FREQ_CAL_MAX_CNT    0U
#define BITP_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1_FREQ_CAL_MAX_CNT    0U
#define BITP_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2_FREQ_CAL_MAX_CNT    0U
#define BITP_PLL_MEM_MAP_CP_VLEVEL_LOW_TC       0U
#define BITP_PLL_MEM_MAP_CP_VLEVEL_HIGH_TC      4U
#define BITP_PLL_MEM_MAP_VCO_CAL_INIT_DEL       5U
#define BITP_PLL_MEM_MAP_VCO_CAL_ALC_INIT_WAIT  3U
#define BITP_PLL_MEM_MAP_QUICK_FREQ_CAL_THRESHOLD       0U
#define BITP_PLL_MEM_MAP_VCO_CAL_ALC_CLK_DIV    0U
#define BITP_PLL_MEM_MAP_VCO_CAL_ALC_WAIT       4U
#define BITP_PLL_MEM_MAP_FORCE_VCO_INIT_ALC_VALUE       7U
#define BITP_PLL_MEM_MAP_VCO_ALC_CAL_EN 6U
#define BITP_PLL_MEM_MAP_CP_VLEVEL_HIGH_FLAG    0U
#define BITP_PLL_MEM_MAP_CP_VLEVEL_LOW_FLAG     4U
#define BITP_PLL_MEM_MAP_CP_AUXADC_HYST_TC      0U
#define BITP_PLL_MEM_MAP_CP_AUXADC_HYST_ON_TC   2U
#define BITP_PLL_MEM_MAP_AUXADC_HYST_FLAG       4U
#define BITP_PLL_MEM_MAP_AUXADC_HYST_ON_FLAG    0U
#define BITP_PLL_MEM_MAP_MCS_WAIT_COUNT 3U
#define BITP_PLL_MEM_MAP_SEL_ADC_FLAG   2U
#define BITP_PLL_MEM_MAP_LDO_SPARE      0U
#define BITP_PLL_MEM_MAP_LD_LOL_HYST_EN 0U
#define BITP_PLL_MEM_MAP_LD_EN  2U
#define BITP_PLL_MEM_MAP_LD_LOL_EN      3U
#define BITP_PLL_MEM_MAP_LD_LOL_LDP     5U
#define BITP_PLL_MEM_MAP_LD_COUNT       4U
#define BITP_PLL_MEM_MAP_CP_F_CAL       6U
#define BITP_PLL_MEM_MAP_CP_F_CAL_BITS  0U
#define BITP_PLL_MEM_MAP_TC_FLAG_STEP   4U
#define BITP_PLL_MEM_MAP_TC_FLAG_STEP_EN        1U
#define BITP_PLL_MEM_MAP_SYNTH_PD       7U
#define BITP_PLL_MEM_MAP_SDM_PD 6U
#define BITP_PLL_MEM_MAP_CP_LEVELDET_PD 5U
#define BITP_PLL_MEM_MAP_REF_CLK_DIVIDER_PD     4U
#define BITP_PLL_MEM_MAP_PRESCALER_PD   2U
#define BITP_PLL_MEM_MAP_VCOTC_DAC_PD   1U
#define BITP_PLL_MEM_MAP_VCOTC_I2V_PD   3U
#define BITP_PLL_MEM_MAP_LD_PD  1U
#define BITP_PLL_MEM_MAP_CP_EN  0U
#define BITP_PLL_MEM_MAP_DIGCORE_INTERFACE_KILLCLK      6U
#define BITP_PLL_MEM_MAP_DIGCORE_SAMPLE_KILLCLK 5U
#define BITP_PLL_MEM_MAP_LO_SYNC_SAMPLER_FLOPS_PD       6U
#define BITP_PLL_MEM_MAP_LO_SYNC_SAMPLER_LO_INPUT_BUF_PD        7U
#define BITP_PLL_MEM_MAP_ROOT_CLKDIV_RB 0U
#define BITP_PLL_MEM_MAP_ROOT_CLKDIV_KILLCLK    3U
#define BITP_PLL_MEM_MAP_LO_PHSYNC_QUAD2_KILLCLK        6U
#define BITP_PLL_MEM_MAP_LO_PHSYNC_LEAF_KILLCLK 4U
#define BITP_PLL_MEM_MAP_SERDES_PLL_ODIV_RB     1U
#define BITP_PLL_MEM_MAP_LO_PHSYNC_LEAF_RB      5U
#define BITP_PLL_MEM_MAP_LO_PHSYNC_QUAD2_RB     7U
#define BITP_PLL_MEM_MAP_DIGCORE_DIV_RSTB       7U
#define BITP_PLL_MEM_MAP_REF_CLK_DIVIDER_RESETB 7U
#define BITP_PLL_MEM_MAP_PFD_RESETB     3U
#define BITP_PLL_MEM_MAP_NDIV_PS_RB     1U
#define BITP_PLL_MEM_MAP_LD_RSTB        0U
#define BITP_PLL_MEM_MAP_VCOTC_DAC_RST  0U
#define BITP_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0   0U
#define BITP_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0   0U
#define BITP_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0   0U
#define BITP_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC    0U
#define BITP_PLL_MEM_MAP_CP_CAL_VALID   7U
#define BITP_PLL_MEM_MAP_VCO_CAL_BUSY   1U
#define BITP_PLL_MEM_MAP_SYN_LOCK       5U
#define BITP_PLL_MEM_MAP_BLEED_RAMP_DONE        4U
#define BITP_PLL_MEM_MAP_TEMPS_MEASUREMENT_READY        4U
#define BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01_TEMPS_TEMPERATURE   0U
#define BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02_TEMPS_TEMPERATURE   0U
#define BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00_TEMPS_CTRL    0U
#define BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01_TEMPS_CTRL    0U
#define BITP_PLL_MEM_MAP_AB_COUNTER_RESETB      6U
#define BITP_PLL_MEM_MAP_LOCK_DETECT_RESETB     4U
#define BITP_PLL_MEM_MAP_MCS_RESETB     3U
#define BITP_PLL_MEM_MAP_LO_SYNC_RESETB 2U
#define BITP_PLL_MEM_MAP_DIGCORE_INTDIV_BINCODE 0U
#define BITP_PLL_MEM_MAP_DIGCORE_CLKDIV_THERMCODE       4U
#define BITP_PLL_MEM_MAP_SDM_RESETB     5U
#define BITP_PLL_MEM_MAP_VCO_TC_CAL_RESETB      1U

/* read / write macros */
#define READ_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0_MBIAS_IGEN_PTATR_TRIM_DONE(base)        READ_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0((base)), BITP_CORE_MBIAS_IGEN_PTATR_TRIM_DONE, BITM_CORE_MBIAS_IGEN_PTATR_TRIM_DONE)
#define READ_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1_MBIAS_IGEN_PTATR_TRIM_DONE(base)        READ_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1((base)), BITP_CORE_MBIAS_IGEN_PTATR_TRIM_DONE, BITM_CORE_MBIAS_IGEN_PTATR_TRIM_DONE)
#define READ_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0_MBIAS_IGEN_PTATR_CODE_RB(base)  READ_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB0((base)), BITP_CORE_MBIAS_IGEN_PTATR_CODE_RB, BITM_CORE_MBIAS_IGEN_PTATR_CODE_RB)
#define READ_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1_MBIAS_IGEN_PTATR_CODE_RB(base)  READ_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM_RB1((base)), BITP_CORE_MBIAS_IGEN_PTATR_CODE_RB, BITM_CORE_MBIAS_IGEN_PTATR_CODE_RB)
#define READ_PLL_MEM_MAP_CLKOUT_BUF_PD(base)    READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD_KILLS((base)), BITP_PLL_MEM_MAP_CLKOUT_BUF_PD, BITM_PLL_MEM_MAP_CLKOUT_BUF_PD)
#define READ_PLL_MEM_MAP_TEST_CLKDIV_RSTB(base) READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV((base)), BITP_PLL_MEM_MAP_TEST_CLKDIV_RSTB, BITM_PLL_MEM_MAP_TEST_CLKDIV_RSTB)
#define READ_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK(base)       READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV((base)), BITP_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK, BITM_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK)
#define READ_PLL_MEM_MAP_VT_FORCE(base) READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CHARGE_PUMP_CONFIG0((base)), BITP_PLL_MEM_MAP_VT_FORCE, BITM_PLL_MEM_MAP_VT_FORCE)
#define READ_PLL_MEM_MAP_TCFORCEN(base) READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCCTL((base)), BITP_PLL_MEM_MAP_TCFORCEN, BITM_PLL_MEM_MAP_TCFORCEN)
#define READ_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC(base)      READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC)
#define READ_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_REF_CLK_REG_REF_CLK_BYTE0((base)), BITP_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO, BITM_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO)
#define READ_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_3((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0)
#define READ_PLL_MEM_MAP_VCOLCR_PD(base)        READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL0((base)), BITP_PLL_MEM_MAP_VCOLCR_PD, BITM_PLL_MEM_MAP_VCOLCR_PD)
#define READ_PLL_MEM_MAP_LDO_POWERGOOD(base)    READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_POWERGOOD, BITM_PLL_MEM_MAP_LDO_POWERGOOD)
#define READ_PLL_MEM_MAP_LDO_UVL(base)  READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_UVL, BITM_PLL_MEM_MAP_LDO_UVL)
#define READ_PLL_MEM_MAP_LDO_CURLIM(base)       READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_CURLIM, BITM_PLL_MEM_MAP_LDO_CURLIM)
#define READ_PLL_MEM_MAP_LDO_LOWOUTPUT(base)    READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_LOWOUTPUT, BITM_PLL_MEM_MAP_LDO_LOWOUTPUT)
#define READ_PLL_MEM_MAP_LDO_OVERVOLT(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_OVERVOLT, BITM_PLL_MEM_MAP_LDO_OVERVOLT)
#define READ_PLL_MEM_MAP_LDO_THERMSDN(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_THERMSDN, BITM_PLL_MEM_MAP_LDO_THERMSDN)
#define READ_PLL_MEM_MAP_LDO_NOREF(base)        READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_STAT((base)), BITP_PLL_MEM_MAP_LDO_NOREF, BITM_PLL_MEM_MAP_LDO_NOREF)
#define READ_PLL_MEM_MAP_SLDO1P0_PD(base)       READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_CTL_1((base)), BITP_PLL_MEM_MAP_SLDO1P0_PD, BITM_PLL_MEM_MAP_SLDO1P0_PD)
#define READ_PLL_MEM_MAP_SLDO1P0_UVFLAG(base)   READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_STAT((base)), BITP_PLL_MEM_MAP_SLDO1P0_UVFLAG, BITM_PLL_MEM_MAP_SLDO1P0_UVFLAG)
#define READ_PLL_MEM_MAP_SLDO1P0_OVFLAG(base)   READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_STAT((base)), BITP_PLL_MEM_MAP_SLDO1P0_OVFLAG, BITM_PLL_MEM_MAP_SLDO1P0_OVFLAG)
#define READ_PLL_MEM_MAP_SLDO0P8_PD(base)       READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL0((base)), BITP_PLL_MEM_MAP_SLDO0P8_PD, BITM_PLL_MEM_MAP_SLDO0P8_PD)
#define READ_PLL_MEM_MAP_PORB_0P8(base) READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL1((base)), BITP_PLL_MEM_MAP_PORB_0P8, BITM_PLL_MEM_MAP_PORB_0P8)
#define READ_PLL_MEM_MAP_CP_CAL_VALID(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL1((base)), BITP_PLL_MEM_MAP_CP_CAL_VALID, BITM_PLL_MEM_MAP_CP_CAL_VALID)
#define READ_PLL_MEM_MAP_CP_CAL_INIT(base)      READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0((base)), BITP_PLL_MEM_MAP_CP_CAL_INIT, BITM_PLL_MEM_MAP_CP_CAL_INIT)
#define READ_PLL_MEM_MAP_VCO_TC_TRACKING_EN(base)       READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2((base)), BITP_PLL_MEM_MAP_VCO_TC_TRACKING_EN, BITM_PLL_MEM_MAP_VCO_TC_TRACKING_EN)
#define READ_PLL_MEM_MAP_VCO_CAL_INIT(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0((base)), BITP_PLL_MEM_MAP_VCO_CAL_INIT, BITM_PLL_MEM_MAP_VCO_CAL_INIT)
#define READ_PLL_MEM_MAP_VCO_CAL_BUSY(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0((base)), BITP_PLL_MEM_MAP_VCO_CAL_BUSY, BITM_PLL_MEM_MAP_VCO_CAL_BUSY)
#define READ_PLL_MEM_MAP_VCO_F_FINE_BAND(base)  READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_FINE_BAND((base)), BITP_PLL_MEM_MAP_VCO_F_FINE_BAND, BITM_PLL_MEM_MAP_VCO_F_FINE_BAND)
#define READ_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND(base)  READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND, BITM_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND)
#define READ_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND(base)  READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND, BITM_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND)
#define READ_PLL_MEM_MAP_SYN_LOCK(base) READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LOCKDET_CONFIG((base)), BITP_PLL_MEM_MAP_SYN_LOCK, BITM_PLL_MEM_MAP_SYN_LOCK)
#define READ_PLL_MEM_MAP_BLEED_RAMP_DONE(base)  READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CTL((base)), BITP_PLL_MEM_MAP_BLEED_RAMP_DONE, BITM_PLL_MEM_MAP_BLEED_RAMP_DONE)
#define READ_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_0((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0)
#define READ_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_1((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0)
#define READ_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_2((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0)
#define READ_PLL_MEM_MAP_TEMPS_MEASUREMENT_READY(base)  READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_00((base)), BITP_PLL_MEM_MAP_TEMPS_MEASUREMENT_READY, BITM_PLL_MEM_MAP_TEMPS_MEASUREMENT_READY)
#define READ_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01_TEMPS_TEMPERATURE(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01((base)), BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01_TEMPS_TEMPERATURE, BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_01_TEMPS_TEMPERATURE)
#define READ_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02_TEMPS_TEMPERATURE(base)     READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02((base)), BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02_TEMPS_TEMPERATURE, BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_02_TEMPS_TEMPERATURE)
#define READ_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC(base)      READ_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC)
#define WRITE_CORE_MBIAS_CAL_TRIGGER(base, val) WRITE_BF_8BIT_REG(pREG_CORE_CLOCK_CONTROL_REGISTERS_CLOCK_CONTROL_2((base)), BITP_CORE_MBIAS_CAL_TRIGGER, BITM_CORE_MBIAS_CAL_TRIGGER, ((val)))
#define WRITE_CORE_DIG_CORE_DEVCLK_PD(base, val)        WRITE_BF_8BIT_REG(pREG_CORE_DEVCLK_CONTROL_GROUP_DEVCLK_BUFFER_CONTROL((base)), BITP_CORE_DIG_CORE_DEVCLK_PD, BITM_CORE_DIG_CORE_DEVCLK_PD, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0_MBIAS_IGEN_PD(base, val) WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0((base)), BITP_CORE_MBIAS_IGEN_PD, BITM_CORE_MBIAS_IGEN_PD, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1_MBIAS_IGEN_PD(base, val) WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1((base)), BITP_CORE_MBIAS_IGEN_PD, BITM_CORE_MBIAS_IGEN_PD, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0_MBIAS_TRIM_COMP_PD(base, val)    WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN0((base)), BITP_CORE_MBIAS_TRIM_COMP_PD, BITM_CORE_MBIAS_TRIM_COMP_PD, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1_MBIAS_TRIM_COMP_PD(base, val)    WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_PWRDWN1((base)), BITP_CORE_MBIAS_TRIM_COMP_PD, BITM_CORE_MBIAS_TRIM_COMP_PD, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM0_MBIAS_RTRIM_RESETB(base, val)     WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM0((base)), BITP_CORE_MBIAS_RTRIM_RESETB, BITM_CORE_MBIAS_RTRIM_RESETB, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM1_MBIAS_RTRIM_RESETB(base, val)     WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_IGEN_RTRIM1((base)), BITP_CORE_MBIAS_RTRIM_RESETB, BITM_CORE_MBIAS_RTRIM_RESETB, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM0_MBIAS_BG_CTAT(base, val)        WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM0((base)), BITP_CORE_MBIAS_BG_CTAT, BITM_CORE_MBIAS_BG_CTAT, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM1_MBIAS_BG_CTAT(base, val)        WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_CTAT_TRIM1((base)), BITP_CORE_MBIAS_BG_CTAT, BITM_CORE_MBIAS_BG_CTAT, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM0_MBIAS_BG_PTAT(base, val)        WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM0((base)), BITP_CORE_MBIAS_BG_PTAT, BITM_CORE_MBIAS_BG_PTAT, ((val)))
#define WRITE_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM1_MBIAS_BG_PTAT(base, val)        WRITE_BF_8BIT_REG(pREG_CORE_MASTER_BIAS_CTRL_MBIAS_BG_PTAT_TRIM1((base)), BITP_CORE_MBIAS_BG_PTAT, BITM_CORE_MBIAS_BG_PTAT, ((val)))
#define WRITE_CORE_DEVCLK_BUFFER_ENABLE(base, val)      WRITE_BF_8BIT_REG(pREG_CORE_DEVCLK_CONTROL_GROUP_DEVCLK_BUFFER_CONTROL((base)), BITP_CORE_DEVCLK_BUFFER_ENABLE, BITM_CORE_DEVCLK_BUFFER_ENABLE, ((val)))
#define WRITE_CORE_CLKPLL_REFPATH_PD(base, val) WRITE_BF_8BIT_REG(pREG_CORE_DEVCLK_CONTROL_GROUP_REFCLK_CLKSYNTH_CONTROL((base)), BITP_CORE_CLKPLL_REFPATH_PD, BITM_CORE_CLKPLL_REFPATH_PD, ((val)))
#define WRITE_PLL_MEM_MAP_CLKOUT_BUF_PD(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD_KILLS((base)), BITP_PLL_MEM_MAP_CLKOUT_BUF_PD, BITM_PLL_MEM_MAP_CLKOUT_BUF_PD, ((val)))
#define WRITE_PLL_MEM_MAP_TEST_CLKDIV_RSTB(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV((base)), BITP_PLL_MEM_MAP_TEST_CLKDIV_RSTB, BITM_PLL_MEM_MAP_TEST_CLKDIV_RSTB, ((val)))
#define WRITE_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_TEST_CLKDIV((base)), BITP_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK, BITM_PLL_MEM_MAP_TEST_CLKDIV_SAMPLE_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_VT_FORCE(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CHARGE_PUMP_CONFIG0((base)), BITP_PLL_MEM_MAP_VT_FORCE, BITM_PLL_MEM_MAP_VT_FORCE, ((val)))
#define WRITE_PLL_MEM_MAP_TCFORCEN(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCCTL((base)), BITP_PLL_MEM_MAP_TCFORCEN, BITM_PLL_MEM_MAP_TCFORCEN, ((val)))
#define WRITE_PLL_MEM_MAP_SLDO0P8_PD(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_SHUNT_LDO_SDM_SHUNT_LDO_CTL0((base)), BITP_PLL_MEM_MAP_SLDO0P8_PD, BITM_PLL_MEM_MAP_SLDO0P8_PD, ((val)))
#define WRITE_PLL_MEM_MAP_SLDO1P0_RAMP(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_CTL_1((base)), BITP_PLL_MEM_MAP_SLDO1P0_RAMP, BITM_PLL_MEM_MAP_SLDO1P0_RAMP, ((val)))
#define WRITE_PLL_MEM_MAP_SLDO1P0_PD(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_SHUNT_LDO_VCO_SHUNT_LDO_CTL_1((base)), BITP_PLL_MEM_MAP_SLDO1P0_PD, BITM_PLL_MEM_MAP_SLDO1P0_PD, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_LDO_PD(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_VCO_LDO_PD, BITM_PLL_MEM_MAP_VCO_LDO_PD, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_LDO_OUTPUT_PD(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_3((base)), BITP_PLL_MEM_MAP_VCO_LDO_OUTPUT_PD, BITM_PLL_MEM_MAP_VCO_LDO_OUTPUT_PD, ((val)))
#define WRITE_PLL_MEM_MAP_VCOLCR_PD(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL0((base)), BITP_PLL_MEM_MAP_VCOLCR_PD, BITM_PLL_MEM_MAP_VCOLCR_PD, ((val)))
#define WRITE_PLL_MEM_MAP_LDO_VOUT_ADJ(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_1((base)), BITP_PLL_MEM_MAP_LDO_VOUT_ADJ, BITM_PLL_MEM_MAP_LDO_VOUT_ADJ, ((val)))
#define WRITE_PLL_MEM_MAP_LDO_CLEAR_STATUS(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_4((base)), BITP_PLL_MEM_MAP_LDO_CLEAR_STATUS, BITM_PLL_MEM_MAP_LDO_CLEAR_STATUS, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_START_MEASUREMENT(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_00((base)), BITP_PLL_MEM_MAP_TEMPS_START_MEASUREMENT, BITM_PLL_MEM_MAP_TEMPS_START_MEASUREMENT, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_OFFSET_ADJ(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_03((base)), BITP_PLL_MEM_MAP_TEMPS_OFFSET_ADJ, BITM_PLL_MEM_MAP_TEMPS_OFFSET_ADJ, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_RESET(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MAIN_00((base)), BITP_PLL_MEM_MAP_TEMPS_RESET, BITM_PLL_MEM_MAP_TEMPS_RESET, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_SEL_MUX_VP(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_MUX_IN((base)), BITP_PLL_MEM_MAP_TEMPS_SEL_MUX_VP, BITM_PLL_MEM_MAP_TEMPS_SEL_MUX_VP, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_CLK_PD(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET((base)), BITP_PLL_MEM_MAP_TEMPS_CLK_PD, BITM_PLL_MEM_MAP_TEMPS_CLK_PD, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_PTAT_PD(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET((base)), BITP_PLL_MEM_MAP_TEMPS_PTAT_PD, BITM_PLL_MEM_MAP_TEMPS_PTAT_PD, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_REF_PD(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET((base)), BITP_PLL_MEM_MAP_TEMPS_REF_PD, BITM_PLL_MEM_MAP_TEMPS_REF_PD, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_ADC_PD(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET((base)), BITP_PLL_MEM_MAP_TEMPS_ADC_PD, BITM_PLL_MEM_MAP_TEMPS_ADC_PD, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_STARTUP_PD(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET((base)), BITP_PLL_MEM_MAP_TEMPS_STARTUP_PD, BITM_PLL_MEM_MAP_TEMPS_STARTUP_PD, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_CURR_FLASHO_N(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_BIAS_COMP((base)), BITP_PLL_MEM_MAP_TEMPS_CURR_FLASHO_N, BITM_PLL_MEM_MAP_TEMPS_CURR_FLASHO_N, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_WAIT_TO_MEASURE(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_CTRL((base)), BITP_PLL_MEM_MAP_TEMPS_WAIT_TO_MEASURE, BITM_PLL_MEM_MAP_TEMPS_WAIT_TO_MEASURE, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_WAKE_SETTING(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_CTRL((base)), BITP_PLL_MEM_MAP_TEMPS_WAKE_SETTING, BITM_PLL_MEM_MAP_TEMPS_WAKE_SETTING, ((val)))
#define WRITE_PLL_MEM_MAP_TEMPS_RESET_ADC(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_PD_RESET((base)), BITP_PLL_MEM_MAP_TEMPS_RESET_ADC, BITM_PLL_MEM_MAP_TEMPS_RESET_ADC, ((val)))
#define WRITE_PLL_MEM_MAP_KILLRDIV_VCOCAL(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_MISC_KILL_SIGNALS((base)), BITP_PLL_MEM_MAP_KILLRDIV_VCOCAL, BITM_PLL_MEM_MAP_KILLRDIV_VCOCAL, ((val)))
#define WRITE_PLL_MEM_MAP_VCOBUF_TO_PS_PD(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD_KILLS((base)), BITP_PLL_MEM_MAP_VCOBUF_TO_PS_PD, BITM_PLL_MEM_MAP_VCOBUF_TO_PS_PD, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_TC_TRACKING_EN(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2((base)), BITP_PLL_MEM_MAP_VCO_TC_TRACKING_EN, BITM_PLL_MEM_MAP_VCO_TC_TRACKING_EN, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_F_COARSE_BAND_EN(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_F_COARSE_BAND_EN, BITM_PLL_MEM_MAP_VCO_F_COARSE_BAND_EN, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_FINE_CAL_EN(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0((base)), BITP_PLL_MEM_MAP_VCO_FINE_CAL_EN, BITM_PLL_MEM_MAP_VCO_FINE_CAL_EN, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_F_FINE_BAND_EN(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_FINE_BAND((base)), BITP_PLL_MEM_MAP_VCO_F_FINE_BAND_EN, BITM_PLL_MEM_MAP_VCO_F_FINE_BAND_EN, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_F_FINE_BAND(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_FINE_BAND((base)), BITP_PLL_MEM_MAP_VCO_F_FINE_BAND, BITM_PLL_MEM_MAP_VCO_F_FINE_BAND, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_CAL_INIT(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0((base)), BITP_PLL_MEM_MAP_VCO_CAL_INIT, BITM_PLL_MEM_MAP_VCO_CAL_INIT, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND, BITM_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE1_VCO_F_COARSE_BAND, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND, BITM_PLL_MEM_MAP_PLL_BASE_REGS_VCO_F_COARSE_BAND_BYTE0_VCO_F_COARSE_BAND, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_COARSE_CAL_EN(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0((base)), BITP_PLL_MEM_MAP_VCO_COARSE_CAL_EN, BITM_PLL_MEM_MAP_VCO_COARSE_CAL_EN, ((val)))
#define WRITE_PLL_MEM_MAP_PFD_KILLUPDN(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_PFD_CTL0((base)), BITP_PLL_MEM_MAP_PFD_KILLUPDN, BITM_PLL_MEM_MAP_PFD_KILLUPDN, ((val)))
#define WRITE_PLL_MEM_MAP_CP_I(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CHARGE_PUMP_CONFIG0((base)), BITP_PLL_MEM_MAP_CP_I, BITM_PLL_MEM_MAP_CP_I, ((val)))
#define WRITE_PLL_MEM_MAP_CP_IBLEED(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL1((base)), BITP_PLL_MEM_MAP_CP_IBLEED, BITM_PLL_MEM_MAP_CP_IBLEED, ((val)))
#define WRITE_PLL_MEM_MAP_CP_CAL_CLK_DIVIDE(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0((base)), BITP_PLL_MEM_MAP_CP_CAL_CLK_DIVIDE, BITM_PLL_MEM_MAP_CP_CAL_CLK_DIVIDE, ((val)))
#define WRITE_PLL_MEM_MAP_CP_CAL_INIT(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0((base)), BITP_PLL_MEM_MAP_CP_CAL_INIT, BITM_PLL_MEM_MAP_CP_CAL_INIT, ((val)))
#define WRITE_PLL_MEM_MAP_LF_BYPASS_R1(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_R1((base)), BITP_PLL_MEM_MAP_LF_BYPASS_R1, BITM_PLL_MEM_MAP_LF_BYPASS_R1, ((val)))
#define WRITE_PLL_MEM_MAP_LF_BYPASS_R3(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_R3((base)), BITP_PLL_MEM_MAP_LF_BYPASS_R3, BITM_PLL_MEM_MAP_LF_BYPASS_R3, ((val)))
#define WRITE_PLL_MEM_MAP_CP_SEL_ADC_TC(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_CTL_STAT((base)), BITP_PLL_MEM_MAP_CP_SEL_ADC_TC, BITM_PLL_MEM_MAP_CP_SEL_ADC_TC, ((val)))
#define WRITE_PLL_MEM_MAP_CP_CAL_EN(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL0((base)), BITP_PLL_MEM_MAP_CP_CAL_EN, BITM_PLL_MEM_MAP_CP_CAL_EN, ((val)))
#define WRITE_PLL_MEM_MAP_BLEED_RAMP_STEP(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CFG((base)), BITP_PLL_MEM_MAP_BLEED_RAMP_STEP, BITM_PLL_MEM_MAP_BLEED_RAMP_STEP, ((val)))
#define WRITE_PLL_MEM_MAP_BLEED_RAMP_TIME_STEP(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CFG((base)), BITP_PLL_MEM_MAP_BLEED_RAMP_TIME_STEP, BITM_PLL_MEM_MAP_BLEED_RAMP_TIME_STEP, ((val)))
#define WRITE_PLL_MEM_MAP_CP_BLEED_DN_EN(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL0((base)), BITP_PLL_MEM_MAP_CP_BLEED_DN_EN, BITM_PLL_MEM_MAP_CP_BLEED_DN_EN, ((val)))
#define WRITE_PLL_MEM_MAP_CP_BLEED_UP_EN(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL0((base)), BITP_PLL_MEM_MAP_CP_BLEED_UP_EN, BITM_PLL_MEM_MAP_CP_BLEED_UP_EN, ((val)))
#define WRITE_PLL_MEM_MAP_BLEED_RAMP_EN(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CTL((base)), BITP_PLL_MEM_MAP_BLEED_RAMP_EN, BITM_PLL_MEM_MAP_BLEED_RAMP_EN, ((val)))
#define WRITE_PLL_MEM_MAP_BLEED_RAMP_INIT(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_BLEED_RAMP_CTL((base)), BITP_PLL_MEM_MAP_BLEED_RAMP_INIT, BITM_PLL_MEM_MAP_BLEED_RAMP_INIT, ((val)))
#define WRITE_PLL_MEM_MAP_LF_C1(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C1((base)), BITP_PLL_MEM_MAP_LF_C1, BITM_PLL_MEM_MAP_LF_C1, ((val)))
#define WRITE_PLL_MEM_MAP_LF_C2(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C2((base)), BITP_PLL_MEM_MAP_LF_C2, BITM_PLL_MEM_MAP_LF_C2, ((val)))
#define WRITE_PLL_MEM_MAP_LF_C3(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C3((base)), BITP_PLL_MEM_MAP_LF_C3, BITM_PLL_MEM_MAP_LF_C3, ((val)))
#define WRITE_PLL_MEM_MAP_LF_R1(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_R1((base)), BITP_PLL_MEM_MAP_LF_R1, BITM_PLL_MEM_MAP_LF_R1, ((val)))
#define WRITE_PLL_MEM_MAP_LF_R3(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_R3((base)), BITP_PLL_MEM_MAP_LF_R3, BITM_PLL_MEM_MAP_LF_R3, ((val)))
#define WRITE_PLL_MEM_MAP_LF_BYPASS_C1(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C1((base)), BITP_PLL_MEM_MAP_LF_BYPASS_C1, BITM_PLL_MEM_MAP_LF_BYPASS_C1, ((val)))
#define WRITE_PLL_MEM_MAP_LF_BYPASS_C2(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LF_C2((base)), BITP_PLL_MEM_MAP_LF_BYPASS_C2, BITM_PLL_MEM_MAP_LF_BYPASS_C2, ((val)))
#define WRITE_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_REF_CLK_REG_REF_CLK_BYTE0((base)), BITP_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO, BITM_PLL_MEM_MAP_REF_CLK_DIVIDE_RATIO, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_TC_WAIT(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2((base)), BITP_PLL_MEM_MAP_VCO_TC_WAIT, BITM_PLL_MEM_MAP_VCO_TC_WAIT, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0_SDM_FRAC(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0_SDM_FRAC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE0_SDM_FRAC, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1_SDM_FRAC(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1_SDM_FRAC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE1_SDM_FRAC, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2_SDM_FRAC(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2_SDM_FRAC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE2_SDM_FRAC, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3_SDM_FRAC(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3_SDM_FRAC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_FRAC_BYTE3_SDM_FRAC, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1_SDM_INT(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1_SDM_INT, BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE1_SDM_INT, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0_SDM_INT(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0_SDM_INT, BITM_PLL_MEM_MAP_PLL_BASE_REGS_DIVIDER_INT_BYTE0_SDM_INT, ((val)))
#define WRITE_PLL_MEM_MAP_LODIV_RB(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL3((base)), BITP_PLL_MEM_MAP_LODIV_RB, BITM_PLL_MEM_MAP_LODIV_RB, ((val)))
#define WRITE_PLL_MEM_MAP_LODIV_FUND(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL4((base)), BITP_PLL_MEM_MAP_LODIV_FUND, BITM_PLL_MEM_MAP_LODIV_FUND, ((val)))
#define WRITE_PLL_MEM_MAP_LODIV_THERMCODE(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL0((base)), BITP_PLL_MEM_MAP_LODIV_THERMCODE, BITM_PLL_MEM_MAP_LODIV_THERMCODE, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_F_ALC_EN(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_F_ALC_EN, BITM_PLL_MEM_MAP_VCO_F_ALC_EN, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_CAL_LOGIC_RESETB(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_VCO_CAL_LOGIC_RESETB, BITM_PLL_MEM_MAP_VCO_CAL_LOGIC_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_SEL(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL0((base)), BITP_PLL_MEM_MAP_VCO_SEL, BITM_PLL_MEM_MAP_VCO_SEL, ((val)))
#define WRITE_PLL_MEM_MAP_LDO_VPTATCTRL(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_3((base)), BITP_PLL_MEM_MAP_LDO_VPTATCTRL, BITM_PLL_MEM_MAP_LDO_VPTATCTRL, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_VAR_TC(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_VAR_TC, BITM_PLL_MEM_MAP_VCO_VAR_TC, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_VAR(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL1((base)), BITP_PLL_MEM_MAP_VCO_VAR, BITM_PLL_MEM_MAP_VCO_VAR, ((val)))
#define WRITE_PLL_MEM_MAP_SERDES_PLL_ODIV(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SERDES_PLL_REGS_PLUS_TEMP_SENSOR_SERDES_OUTPUT_DIVIDER_CTL((base)), BITP_PLL_MEM_MAP_SERDES_PLL_ODIV, BITM_PLL_MEM_MAP_SERDES_PLL_ODIV, ((val)))
#define WRITE_PLL_MEM_MAP_SERDES_PLL_ODIV_KILLCLK(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SERDES_PLL_REGS_PLUS_TEMP_SENSOR_SERDES_OUTPUT_DIVIDER_CTL((base)), BITP_PLL_MEM_MAP_SERDES_PLL_ODIV_KILLCLK, BITM_PLL_MEM_MAP_SERDES_PLL_ODIV_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_VCOPKDET_CM_SEL(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL1((base)), BITP_PLL_MEM_MAP_VCOPKDET_CM_SEL, BITM_PLL_MEM_MAP_VCOPKDET_CM_SEL, ((val)))
#define WRITE_PLL_MEM_MAP_VCOPKDET_VREF_SEL(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL2((base)), BITP_PLL_MEM_MAP_VCOPKDET_VREF_SEL, BITM_PLL_MEM_MAP_VCOPKDET_VREF_SEL, ((val)))
#define WRITE_PLL_MEM_MAP_VCOPKDET_BYP_RES_DET(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_CTL2((base)), BITP_PLL_MEM_MAP_VCOPKDET_BYP_RES_DET, BITM_PLL_MEM_MAP_VCOPKDET_BYP_RES_DET, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0_TCIDAC(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0((base)), BITP_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0_TCIDAC, BITM_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_0_TCIDAC, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1_TCIDAC(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1((base)), BITP_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1_TCIDAC, BITM_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCIDAC_1_TCIDAC, ((val)))
#define WRITE_PLL_MEM_MAP_TCUPDINIT(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_VCO_TC_CAL_REGS_TCCTL((base)), BITP_PLL_MEM_MAP_TCUPDINIT, BITM_PLL_MEM_MAP_TCUPDINIT, ((val)))
#define WRITE_PLL_MEM_MAP_ROOT_CLKDIV_DIV2(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV((base)), BITP_PLL_MEM_MAP_ROOT_CLKDIV_DIV2, BITM_PLL_MEM_MAP_ROOT_CLKDIV_DIV2, ((val)))
#define WRITE_PLL_MEM_MAP_ROOT_CLKDIV_FUND(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV((base)), BITP_PLL_MEM_MAP_ROOT_CLKDIV_FUND, BITM_PLL_MEM_MAP_ROOT_CLKDIV_FUND, ((val)))
#define WRITE_PLL_MEM_MAP_CLKGEN_SERDES_OUTBUF_PD(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_LOGEN_CLKGEN_LOSYNC_PD((base)), BITP_PLL_MEM_MAP_CLKGEN_SERDES_OUTBUF_PD, BITM_PLL_MEM_MAP_CLKGEN_SERDES_OUTBUF_PD, ((val)))
#define WRITE_PLL_MEM_MAP_FREQ_CAL_CNT_RDSEL(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_MOD_VCO_CAL_CTL((base)), BITP_PLL_MEM_MAP_FREQ_CAL_CNT_RDSEL, BITM_PLL_MEM_MAP_FREQ_CAL_CNT_RDSEL, ((val)))
#define WRITE_PLL_MEM_MAP_QUICK_FREQ_CAL_EN(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_QUICK_FREQ_CAL_CTL((base)), BITP_PLL_MEM_MAP_QUICK_FREQ_CAL_EN, BITM_PLL_MEM_MAP_QUICK_FREQ_CAL_EN, ((val)))
#define WRITE_PLL_MEM_MAP_LOCKDET_CNT(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_LOCKDET_CONFIG((base)), BITP_PLL_MEM_MAP_LOCKDET_CNT, BITM_PLL_MEM_MAP_LOCKDET_CNT, ((val)))
#define WRITE_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0_FREQ_CAL_MAX_CNT(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0((base)), BITP_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0_FREQ_CAL_MAX_CNT, BITM_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT0_FREQ_CAL_MAX_CNT, ((val)))
#define WRITE_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1_FREQ_CAL_MAX_CNT(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1((base)), BITP_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1_FREQ_CAL_MAX_CNT, BITM_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT1_FREQ_CAL_MAX_CNT, ((val)))
#define WRITE_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2_FREQ_CAL_MAX_CNT(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2((base)), BITP_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2_FREQ_CAL_MAX_CNT, BITM_PLL_MEM_MAP_NEW_VCO_CAL_REGS_FREQ_CAL_MAX_CNT2_FREQ_CAL_MAX_CNT, ((val)))
#define WRITE_PLL_MEM_MAP_CP_VLEVEL_LOW_TC(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC((base)), BITP_PLL_MEM_MAP_CP_VLEVEL_LOW_TC, BITM_PLL_MEM_MAP_CP_VLEVEL_LOW_TC, ((val)))
#define WRITE_PLL_MEM_MAP_CP_VLEVEL_HIGH_TC(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC((base)), BITP_PLL_MEM_MAP_CP_VLEVEL_HIGH_TC, BITM_PLL_MEM_MAP_CP_VLEVEL_HIGH_TC, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_CAL_INIT_DEL(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_CAL_INIT_DEL, BITM_PLL_MEM_MAP_VCO_CAL_INIT_DEL, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_CAL_ALC_INIT_WAIT(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_CAL_ALC_INIT_WAIT, BITM_PLL_MEM_MAP_VCO_CAL_ALC_INIT_WAIT, ((val)))
#define WRITE_PLL_MEM_MAP_QUICK_FREQ_CAL_THRESHOLD(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_QUICK_FREQ_CAL_CTL((base)), BITP_PLL_MEM_MAP_QUICK_FREQ_CAL_THRESHOLD, BITM_PLL_MEM_MAP_QUICK_FREQ_CAL_THRESHOLD, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_CAL_ALC_CLK_DIV(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_CAL_ALC_CLK_DIV, BITM_PLL_MEM_MAP_VCO_CAL_ALC_CLK_DIV, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_CAL_ALC_WAIT(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_ALC_FREQ_CAL_BYTE0((base)), BITP_PLL_MEM_MAP_VCO_CAL_ALC_WAIT, BITM_PLL_MEM_MAP_VCO_CAL_ALC_WAIT, ((val)))
#define WRITE_PLL_MEM_MAP_FORCE_VCO_INIT_ALC_VALUE(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_VCO_CAL_REGS_MOD_VCO_CAL_CTL((base)), BITP_PLL_MEM_MAP_FORCE_VCO_INIT_ALC_VALUE, BITM_PLL_MEM_MAP_FORCE_VCO_INIT_ALC_VALUE, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_ALC_CAL_EN(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1((base)), BITP_PLL_MEM_MAP_VCO_ALC_CAL_EN, BITM_PLL_MEM_MAP_VCO_ALC_CAL_EN, ((val)))
#define WRITE_PLL_MEM_MAP_CP_VLEVEL_HIGH_FLAG(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC2((base)), BITP_PLL_MEM_MAP_CP_VLEVEL_HIGH_FLAG, BITM_PLL_MEM_MAP_CP_VLEVEL_HIGH_FLAG, ((val)))
#define WRITE_PLL_MEM_MAP_CP_VLEVEL_LOW_FLAG(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_TC2((base)), BITP_PLL_MEM_MAP_CP_VLEVEL_LOW_FLAG, BITM_PLL_MEM_MAP_CP_VLEVEL_LOW_FLAG, ((val)))
#define WRITE_PLL_MEM_MAP_CP_AUXADC_HYST_TC(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_CTL_STAT((base)), BITP_PLL_MEM_MAP_CP_AUXADC_HYST_TC, BITM_PLL_MEM_MAP_CP_AUXADC_HYST_TC, ((val)))
#define WRITE_PLL_MEM_MAP_CP_AUXADC_HYST_ON_TC(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_LVL_DET_CTL_STAT((base)), BITP_PLL_MEM_MAP_CP_AUXADC_HYST_ON_TC, BITM_PLL_MEM_MAP_CP_AUXADC_HYST_ON_TC, ((val)))
#define WRITE_PLL_MEM_MAP_AUXADC_HYST_FLAG(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL2((base)), BITP_PLL_MEM_MAP_AUXADC_HYST_FLAG, BITM_PLL_MEM_MAP_AUXADC_HYST_FLAG, ((val)))
#define WRITE_PLL_MEM_MAP_AUXADC_HYST_ON_FLAG(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL2((base)), BITP_PLL_MEM_MAP_AUXADC_HYST_ON_FLAG, BITM_PLL_MEM_MAP_AUXADC_HYST_ON_FLAG, ((val)))
#define WRITE_PLL_MEM_MAP_MCS_WAIT_COUNT(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_MCS_CONTROL_2((base)), BITP_PLL_MEM_MAP_MCS_WAIT_COUNT, BITM_PLL_MEM_MAP_MCS_WAIT_COUNT, ((val)))
#define WRITE_PLL_MEM_MAP_SEL_ADC_FLAG(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL2((base)), BITP_PLL_MEM_MAP_SEL_ADC_FLAG, BITM_PLL_MEM_MAP_SEL_ADC_FLAG, ((val)))
#define WRITE_PLL_MEM_MAP_LDO_SPARE(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_VCO_LDO_3((base)), BITP_PLL_MEM_MAP_LDO_SPARE, BITM_PLL_MEM_MAP_LDO_SPARE, ((val)))
#define WRITE_PLL_MEM_MAP_LD_LOL_HYST_EN(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT1((base)), BITP_PLL_MEM_MAP_LD_LOL_HYST_EN, BITM_PLL_MEM_MAP_LD_LOL_HYST_EN, ((val)))
#define WRITE_PLL_MEM_MAP_LD_EN(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0((base)), BITP_PLL_MEM_MAP_LD_EN, BITM_PLL_MEM_MAP_LD_EN, ((val)))
#define WRITE_PLL_MEM_MAP_LD_LOL_EN(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0((base)), BITP_PLL_MEM_MAP_LD_LOL_EN, BITM_PLL_MEM_MAP_LD_LOL_EN, ((val)))
#define WRITE_PLL_MEM_MAP_LD_LOL_LDP(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0((base)), BITP_PLL_MEM_MAP_LD_LOL_LDP, BITM_PLL_MEM_MAP_LD_LOL_LDP, ((val)))
#define WRITE_PLL_MEM_MAP_LD_COUNT(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT1((base)), BITP_PLL_MEM_MAP_LD_COUNT, BITM_PLL_MEM_MAP_LD_COUNT, ((val)))
#define WRITE_PLL_MEM_MAP_CP_F_CAL(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL1((base)), BITP_PLL_MEM_MAP_CP_F_CAL, BITM_PLL_MEM_MAP_CP_F_CAL, ((val)))
#define WRITE_PLL_MEM_MAP_CP_F_CAL_BITS(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_CP_CAL_CTL1((base)), BITP_PLL_MEM_MAP_CP_F_CAL_BITS, BITM_PLL_MEM_MAP_CP_F_CAL_BITS, ((val)))
#define WRITE_PLL_MEM_MAP_TC_FLAG_STEP(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE3((base)), BITP_PLL_MEM_MAP_TC_FLAG_STEP, BITM_PLL_MEM_MAP_TC_FLAG_STEP, ((val)))
#define WRITE_PLL_MEM_MAP_TC_FLAG_STEP_EN(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_VCO_TC_BYTE2((base)), BITP_PLL_MEM_MAP_TC_FLAG_STEP_EN, BITM_PLL_MEM_MAP_TC_FLAG_STEP_EN, ((val)))
#define WRITE_PLL_MEM_MAP_SYNTH_PD(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_SYNTH_PD, BITM_PLL_MEM_MAP_SYNTH_PD, ((val)))
#define WRITE_PLL_MEM_MAP_SDM_PD(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_SDM_PD, BITM_PLL_MEM_MAP_SDM_PD, ((val)))
#define WRITE_PLL_MEM_MAP_CP_LEVELDET_PD(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_CP_LEVELDET_PD, BITM_PLL_MEM_MAP_CP_LEVELDET_PD, ((val)))
#define WRITE_PLL_MEM_MAP_REF_CLK_DIVIDER_PD(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_REF_CLK_DIVIDER_PD, BITM_PLL_MEM_MAP_REF_CLK_DIVIDER_PD, ((val)))
#define WRITE_PLL_MEM_MAP_PRESCALER_PD(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_PRESCALER_PD, BITM_PLL_MEM_MAP_PRESCALER_PD, ((val)))
#define WRITE_PLL_MEM_MAP_VCOTC_DAC_PD(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_VCOTC_DAC_PD, BITM_PLL_MEM_MAP_VCOTC_DAC_PD, ((val)))
#define WRITE_PLL_MEM_MAP_VCOTC_I2V_PD(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_TCIDAC_REG0((base)), BITP_PLL_MEM_MAP_VCOTC_I2V_PD, BITM_PLL_MEM_MAP_VCOTC_I2V_PD, ((val)))
#define WRITE_PLL_MEM_MAP_LD_PD(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT1((base)), BITP_PLL_MEM_MAP_LD_PD, BITM_PLL_MEM_MAP_LD_PD, ((val)))
#define WRITE_PLL_MEM_MAP_CP_EN(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_CP_CTL0((base)), BITP_PLL_MEM_MAP_CP_EN, BITM_PLL_MEM_MAP_CP_EN, ((val)))
#define WRITE_PLL_MEM_MAP_DIGCORE_INTERFACE_KILLCLK(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_1((base)), BITP_PLL_MEM_MAP_DIGCORE_INTERFACE_KILLCLK, BITM_PLL_MEM_MAP_DIGCORE_INTERFACE_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_DIGCORE_SAMPLE_KILLCLK(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_1((base)), BITP_PLL_MEM_MAP_DIGCORE_SAMPLE_KILLCLK, BITM_PLL_MEM_MAP_DIGCORE_SAMPLE_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_LO_SYNC_SAMPLER_FLOPS_PD(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_LOGEN_CLKGEN_LOSYNC_PD((base)), BITP_PLL_MEM_MAP_LO_SYNC_SAMPLER_FLOPS_PD, BITM_PLL_MEM_MAP_LO_SYNC_SAMPLER_FLOPS_PD, ((val)))
#define WRITE_PLL_MEM_MAP_LO_SYNC_SAMPLER_LO_INPUT_BUF_PD(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_LOGEN_CLKGEN_LOSYNC_PD((base)), BITP_PLL_MEM_MAP_LO_SYNC_SAMPLER_LO_INPUT_BUF_PD, BITM_PLL_MEM_MAP_LO_SYNC_SAMPLER_LO_INPUT_BUF_PD, ((val)))
#define WRITE_PLL_MEM_MAP_ROOT_CLKDIV_RB(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV((base)), BITP_PLL_MEM_MAP_ROOT_CLKDIV_RB, BITM_PLL_MEM_MAP_ROOT_CLKDIV_RB, ((val)))
#define WRITE_PLL_MEM_MAP_ROOT_CLKDIV_KILLCLK(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_ROOT_DIV((base)), BITP_PLL_MEM_MAP_ROOT_CLKDIV_KILLCLK, BITM_PLL_MEM_MAP_ROOT_CLKDIV_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_LO_PHSYNC_QUAD2_KILLCLK(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5((base)), BITP_PLL_MEM_MAP_LO_PHSYNC_QUAD2_KILLCLK, BITM_PLL_MEM_MAP_LO_PHSYNC_QUAD2_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_LO_PHSYNC_LEAF_KILLCLK(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5((base)), BITP_PLL_MEM_MAP_LO_PHSYNC_LEAF_KILLCLK, BITM_PLL_MEM_MAP_LO_PHSYNC_LEAF_KILLCLK, ((val)))
#define WRITE_PLL_MEM_MAP_SERDES_PLL_ODIV_RB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SERDES_PLL_REGS_PLUS_TEMP_SENSOR_SERDES_OUTPUT_DIVIDER_CTL((base)), BITP_PLL_MEM_MAP_SERDES_PLL_ODIV_RB, BITM_PLL_MEM_MAP_SERDES_PLL_ODIV_RB, ((val)))
#define WRITE_PLL_MEM_MAP_LO_PHSYNC_LEAF_RB(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5((base)), BITP_PLL_MEM_MAP_LO_PHSYNC_LEAF_RB, BITM_PLL_MEM_MAP_LO_PHSYNC_LEAF_RB, ((val)))
#define WRITE_PLL_MEM_MAP_LO_PHSYNC_QUAD2_RB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_LOGEN_REGS_LOGEN_CTL5((base)), BITP_PLL_MEM_MAP_LO_PHSYNC_QUAD2_RB, BITM_PLL_MEM_MAP_LO_PHSYNC_QUAD2_RB, ((val)))
#define WRITE_PLL_MEM_MAP_DIGCORE_DIV_RSTB(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_1((base)), BITP_PLL_MEM_MAP_DIGCORE_DIV_RSTB, BITM_PLL_MEM_MAP_DIGCORE_DIV_RSTB, ((val)))
#define WRITE_PLL_MEM_MAP_REF_CLK_DIVIDER_RESETB(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_REF_CLK_DIVIDER_RESETB, BITM_PLL_MEM_MAP_REF_CLK_DIVIDER_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_PFD_RESETB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_MISC_PD((base)), BITP_PLL_MEM_MAP_PFD_RESETB, BITM_PLL_MEM_MAP_PFD_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_NDIV_PS_RB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_PRESCALER_CTL((base)), BITP_PLL_MEM_MAP_NDIV_PS_RB, BITM_PLL_MEM_MAP_NDIV_PS_RB, ((val)))
#define WRITE_PLL_MEM_MAP_LD_RSTB(base, val)    WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_NEW_LOCK_DETECT0((base)), BITP_PLL_MEM_MAP_LD_RSTB, BITM_PLL_MEM_MAP_LD_RSTB, ((val)))
#define WRITE_PLL_MEM_MAP_VCOTC_DAC_RST(base, val)      WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_NEW_PLL_BASE_REGS_TCIDAC_REG0((base)), BITP_PLL_MEM_MAP_VCOTC_DAC_RST, BITM_PLL_MEM_MAP_VCOTC_DAC_RST, ((val)))
#define WRITE_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_0((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_0_MOD0, ((val)))
#define WRITE_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_1((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_1_MOD0, ((val)))
#define WRITE_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_2((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_2_MOD0, ((val)))
#define WRITE_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0(base, val)       WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_SDM_REGS_MOD0_3((base)), BITP_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0, BITM_PLL_MEM_MAP_SDM_REGS_MOD0_3_MOD0, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE0_VCO_F_ALC, ((val)))
#define WRITE_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1((base)), BITP_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC, BITM_PLL_MEM_MAP_PLL_BASE_REGS_F_ALC_BYTE1_VCO_F_ALC, ((val)))
#define WRITE_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00_TEMPS_CTRL(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00((base)), BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00_TEMPS_CTRL, BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_00_TEMPS_CTRL, ((val)))
#define WRITE_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01_TEMPS_CTRL(base, val)        WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01((base)), BITP_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01_TEMPS_CTRL, BITM_PLL_MEM_MAP_TEMP_SENSE_REGISTERS_TEMPS_TEST_SPARE_01_TEMPS_CTRL, ((val)))
#define WRITE_PLL_MEM_MAP_AB_COUNTER_RESETB(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_AB_COUNTER_RESETB, BITM_PLL_MEM_MAP_AB_COUNTER_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_LOCK_DETECT_RESETB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_LOCK_DETECT_RESETB, BITM_PLL_MEM_MAP_LOCK_DETECT_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_MCS_RESETB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_MCS_RESETB, BITM_PLL_MEM_MAP_MCS_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_LO_SYNC_RESETB(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_LO_SYNC_RESETB, BITM_PLL_MEM_MAP_LO_SYNC_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_DIGCORE_INTDIV_BINCODE(base, val)     WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_2((base)), BITP_PLL_MEM_MAP_DIGCORE_INTDIV_BINCODE, BITM_PLL_MEM_MAP_DIGCORE_INTDIV_BINCODE, ((val)))
#define WRITE_PLL_MEM_MAP_DIGCORE_CLKDIV_THERMCODE(base, val)   WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_CLKGEN_REGS_CLKGEN_DIGCORE_2((base)), BITP_PLL_MEM_MAP_DIGCORE_CLKDIV_THERMCODE, BITM_PLL_MEM_MAP_DIGCORE_CLKDIV_THERMCODE, ((val)))
#define WRITE_PLL_MEM_MAP_SDM_RESETB(base, val) WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_SDM_RESETB, BITM_PLL_MEM_MAP_SDM_RESETB, ((val)))
#define WRITE_PLL_MEM_MAP_VCO_TC_CAL_RESETB(base, val)  WRITE_BF_8BIT_REG(pREG_PLL_MEM_MAP_PD_EN_RESETB_REGS_SYNTH_RESETB((base)), BITP_PLL_MEM_MAP_VCO_TC_CAL_RESETB, BITM_PLL_MEM_MAP_VCO_TC_CAL_RESETB, ((val)))


#endif /* __ADI_ADRV906X_PLL_INTERNAL_H__ */
